set( FFI_SRC_FILES

    src/wrapper.cpp

    src/apppath.cpp
    src/defs.cpp
    src/dragimage.cpp
    src/extra.cpp

    src/glcanvas.cpp
    src/graphicscontext.cpp
    src/hyperlinkctrl.cpp
    src/image.cpp
    src/mediactrl.cpp
    src/pickerctrl.cpp
    src/previewframe.cpp
    src/printout.cpp
    src/sckaddr.cpp
    src/socket.cpp
    src/sound.cpp
    src/stc.cpp
    src/std.cpp
    src/stream.cpp
    src/taskbaricon.cpp
    src/textstream.cpp
    src/treectrl.cpp

    src/wx_aboutbox.cpp
    src/wx_accelerator.cpp
    src/wx_activityindicator.cpp
    src/wx_animationctrl.cpp
    src/wx_artprov.cpp
    src/wx_aui.cpp
    src/wx_auimdi.cpp
    src/wx_bannerwindow.cpp
    src/wx_bitmap.cpp
    src/wx_bitmapcombobox.cpp
    src/wx_brush.cpp
    src/wx_busyinfo.cpp
    src/wx_button.cpp
    src/wx_calendarctrl.cpp
    src/wx_caret.cpp
    src/wx_checkbox.cpp
    src/wx_checklistbox.cpp
    src/wx_choice.cpp
    src/wx_choicebook.cpp
    src/wx_clipboard.cpp
    src/wx_coldata.cpp
    src/wx_collapsiblepane.cpp
    src/wx_colour.cpp
    src/wx_colourdlg.cpp
    src/wx_combobox.cpp
    src/wx_comboctrl.cpp
    src/wx_commandlinkbutton.cpp
    src/wx_configbase.cpp
    src/wx_control.cpp
    src/wx_ctxhelp.cpp
    src/wx_cursor.cpp
    src/wx_dataformat.cpp
    src/wx_dataviewctrl.cpp
    src/wx_dataviewlistctrl.cpp
    src/wx_datepickerctrl.cpp
    src/wx_datetime.cpp
    src/wx_dc.cpp
    src/wx_dcsvg.cpp
    src/wx_dialog.cpp
    src/wx_dirdlg.cpp
    src/wx_dirpickerctrl.cpp
    src/wx_display.cpp
    src/wx_dnd.cpp
    src/wx_docframes.cpp
    src/wx_drawing.cpp
    src/wx_event.cpp
    src/wx_filectrl.cpp
    src/wx_filedialog.cpp
    src/wx_filehist.cpp
    src/wx_filepickerctrl.cpp
    src/wx_findrepldlg.cpp
    src/wx_font.cpp
    src/wx_fontdata.cpp
    src/wx_fontdlg.cpp
    src/wx_fontpickerctrl.cpp
    src/wx_frame.cpp
    src/wx_gauge.cpp
    src/wx_genericdirctrl.cpp
    src/wx_grid.cpp
    src/wx_gridbagsizer.cpp
    src/wx_headerctrl.cpp
    src/wx_helpcontroller.cpp
    src/wx_icnbndl.cpp
    src/wx_icon.cpp
    src/wx_image.cpp
    src/wx_imagelist.cpp
    src/wx_infobar.cpp
    src/wx_itemcontainer.cpp
    src/wx_layoutconstraints.cpp
    src/wx_listbook.cpp
    src/wx_listbox.cpp
    src/wx_listctrl.cpp
    src/wx_listview.cpp
    src/wx_locale.cpp
    src/wx_log.cpp
    src/wx_mask.cpp
    src/wx_mdi.cpp
    src/wx_menu.cpp
    src/wx_menubar.cpp
    src/wx_messagedialog.cpp
    src/wx_mime.cpp
    src/wx_miniframe.cpp
    src/wx_notebook.cpp
    src/wx_notifmsg.cpp
    src/wx_palette.cpp
    src/wx_panel.cpp
    src/wx_pen.cpp
    src/wx_popup.cpp
    src/wx_printdlg.cpp
    src/wx_printing.cpp
    src/wx_process.cpp
    src/wx_propertygridmanager.cpp
    src/wx_propertysheetdialog.cpp
    src/wx_radiobox.cpp
    src/wx_radiobutton.cpp
    src/wx_rc.cpp
    src/wx_rearrangectrl.cpp
    src/wx_region.cpp
    src/wx_regioniter.cpp
    src/wx_ribbonbar.cpp
    src/wx_ribbonbuttonbar.cpp
    src/wx_ribbongallery.cpp
    src/wx_ribbonpage.cpp
    src/wx_ribbonpanel.cpp
    src/wx_ribbontoolbar.cpp
    src/wx_richtextctrl.cpp
    src/wx_sash.cpp
    src/wx_scrollbar.cpp
    src/wx_scrolledwindow.cpp
    src/wx_searchctrl.cpp
    src/wx_simplebook.cpp
    src/wx_simplehtmllistbox.cpp
    src/wx_singleinst.cpp
    src/wx_sizer.cpp
    src/wx_slider.cpp
    src/wx_spinctrl.cpp
    src/wx_spinctrldouble.cpp
    src/wx_splash.cpp
    src/wx_splitterwindow.cpp
    src/wx_staticbox.cpp
    src/wx_staticline.cpp
    src/wx_statictext.cpp
    src/wx_statusbar.cpp
    src/wx_stddialogbuttonsizer.cpp
    src/wx_systemsettings.cpp
    src/wx_textctrl.cpp
    src/wx_textdlg.cpp
    src/wx_textentry.cpp
    src/wx_tglbtn.cpp
    src/wx_timepickerctrl.cpp
    src/wx_timer.cpp
    src/wx_tipwnd.cpp
    src/wx_toolbar.cpp
    src/wx_toolbook.cpp
    src/wx_tooltip.cpp
    src/wx_treebook.cpp
    src/wx_treelistctrl.cpp
    src/wx_uiaction.cpp
    src/wx_validator.cpp
    src/wx_vlistbox.cpp
    src/wx_vscroll.cpp
    src/wx_webview.cpp
    src/wx_window.cpp
    src/wx_windowdisabler.cpp
    src/wx_wizard.cpp
    src/wx_wrapsizer.cpp
)

set( FFI_HDR_FILES

    include/wrapper.h
    include/wxffi_types.h
    include/wxffi_def.h
    include/wxffi_glue.h
    include/wxffi_grid.h
)
