// Generated by GitHub Copilot. Directed and reviewed by Ralph Walden.
// Licensed under Apache 2.0. This file is not subject to copyright.

#pragma once

// Common inline utilities shared across all kwxgen language emitters.
// Include this header in lang_*.cpp files only.

#include "../model.h"

#include <cctype>
#include <ostream>
#include <string>
#include <string_view>

namespace kwxgen
{

    // Returns true if a FunctionDecl is well-formed (no comment artifacts, non-empty method name).
    inline bool IsValidFunction(const FunctionDecl& f)
    {
        if (f.return_type.find("//") != std::string::npos ||
            f.return_type.find("/*") != std::string::npos ||
            f.return_type.find("*/") != std::string::npos)
            return false;
        if (f.method_name.find("//") != std::string::npos ||
            f.method_name.find("/*") != std::string::npos)
            return false;
        if (f.method_name.empty())
            return false;
        for (const auto& p: f.params)
        {
            if (p.raw_type.find("//") != std::string::npos ||
                p.raw_type.find("/*") != std::string::npos)
                return false;
        }
        return true;
    }

    // Build the C exported function name: "wxButton_Create", or just method_name for free
    // functions (class_name is empty).
    inline std::string CFuncName(const FunctionDecl& f)
    {
        if (f.class_name.empty())
            return f.method_name;
        return f.class_name + "_" + f.method_name;
    }

    // Write the standard "do not edit" header comment to a generated file.
    //   commentPrefix  — the single-line comment leader for the target language ("//", "#", "--")
    //   extraNewline   — emit a second blank line after the header (Go/Rust/Julia style)
    inline void WriteGeneratedHeader(std::ostream& out, std::string_view commentPrefix = "//",
                                     bool extraNewline = true)
    {
        out << commentPrefix << " Code generated by kwxgen. DO NOT EDIT.\n";
        if (extraNewline)
            out << "\n";
    }

    // Lowercase an entire string: "TextCtrl" → "textctrl".
    inline std::string ToLower(const std::string& s)
    {
        std::string result;
        result.reserve(s.size());
        for (char c: s)
            result += static_cast<char>(std::tolower(static_cast<unsigned char>(c)));
        return result;
    }

    // Convert CamelCase to snake_case: "SetDefault" → "set_default".
    // Handles acronyms correctly: "GetHTML" → "get_html".
    inline std::string ToSnakeCase(const std::string& name)
    {
        std::string result;
        for (size_t i = 0; i < name.size(); ++i)
        {
            char ch = name[i];
            if (std::isupper(static_cast<unsigned char>(ch)))
            {
                if (i > 0)
                {
                    char prev = name[i - 1];
                    bool prevLower = std::islower(static_cast<unsigned char>(prev)) != 0;
                    bool nextLower = (i + 1 < name.size()) &&
                                     std::islower(static_cast<unsigned char>(name[i + 1])) != 0;
                    if (prevLower || (std::isupper(static_cast<unsigned char>(prev)) && nextLower))
                        result += '_';
                }
                result += static_cast<char>(std::tolower(static_cast<unsigned char>(ch)));
            }
            else
            {
                result += ch;
            }
        }
        return result;
    }

}  // namespace kwxgen
