// Generated by GitHub Copilot. Directed and reviewed by Ralph Walden.
// Licensed under Apache 2.0. This file is not subject to copyright.

#include "lang_perl.h"

#include "../file_writer.h"
#include "lang_common.h"
#include "perl_type_map.h"

#include <algorithm>
#include <cctype>
#include <filesystem>
#include <iostream>
#include <set>
#include <unordered_set>
#include <vector>

namespace fs = std::filesystem;

namespace kwxgen
{

    namespace
    {

        // Strip "wx" / "ELJ" / "kwx" prefix from a class name.
        std::string PerlStripPrefix(const std::string& name)
        {
            if (name.size() > 2 && name[0] == 'w' && name[1] == 'x')
                return name.substr(2);
            if (name.size() > 3 && name[0] == 'E' && name[1] == 'L' && name[2] == 'J')
                return name.substr(3);
            if (name.size() > 3 && name[0] == 'k' && name[1] == 'w' && name[2] == 'x')
                return name.substr(3);
            return name;
        }

        // "wxButton" -> "Button.pm"
        std::string PerlPMFileName(const std::string& class_name)
        {
            return PerlStripPrefix(class_name) + ".pm";
        }

        // "wxButton" -> "wx::FFI::Raw::Button"
        std::string PerlRawPackageName(const std::string& class_name)
        {
            return "wx::FFI::Raw::" + PerlStripPrefix(class_name);
        }

        // "wxButton" -> "wx::Button"
        std::string PerlOOPackageName(const std::string& class_name)
        {
            return "wx::" + PerlStripPrefix(class_name);
        }

        bool IsVoidReturn(const std::string& return_type)
        {
            return return_type.empty() || return_type == "void";
        }

        bool IsStringReturn(const FunctionDecl& func)
        {
            if (func.return_type == "TString" || func.return_type == "TStringOut")
                return true;
            if (func.return_macro == "TClass" && func.return_arg == "wxString")
                return true;
            return false;
        }

        bool IsBoolReturn(const FunctionDecl& func)
        {
            return func.return_type == "TBool" || func.return_type == "TBoolInt";
        }

        // True if function returns a class pointer (not wxString).
        bool IsClassReturn(const FunctionDecl& func)
        {
            return (func.return_macro == "TClass" || func.return_macro == "TSelf" ||
                    func.return_macro == "TClassRef") &&
                   func.return_arg != "wxString" && !func.return_arg.empty();
        }

        // True if first param is TClass(ClassName) matching the function's own class (pseudo-self).
        bool HasPseudoSelf(const FunctionDecl& func)
        {
            if (func.has_self || func.class_name.empty() || func.params.empty())
                return false;
            const auto& first = func.params[0];
            return first.macro_name == "TClass" && first.macro_arg == func.class_name;
        }

        // Find the nearest parent class that has methods (is actually wrapped).
        std::string FindWrappedParent(const std::string& class_name, const ParsedFFI& ffi,
                                      const std::unordered_set<std::string>& wrapped_classes)
        {
            auto iter = ffi.parent_map.find(class_name);
            std::set<std::string> visited;
            while (iter != ffi.parent_map.end())
            {
                const auto& parent = iter->second;
                if (visited.count(parent))
                    break;
                visited.insert(parent);
                if (wrapped_classes.count(parent))
                    return parent;
                iter = ffi.parent_map.find(parent);
            }
            return "";
        }

        // -----------------------------------------------------------------
        // OO Layer Helpers: method parameter conversion
        // -----------------------------------------------------------------

        struct PerlIdiomParam
        {
            std::string name;       // Perl parameter name
            std::string call_expr;  // Expression passed to the raw FFI call
            std::string pre_call;   // Statement before the call (empty if none)
            std::string post_call;  // Statement after the call (empty if none)
        };

        // Convert one Param into idiomatic Perl method parameters.
        // TSelf is skipped; TClass(wxString) gets wxString lifecycle handling.
        std::vector<PerlIdiomParam> ConvertToPerlMethodParam(const Param& param)
        {
            std::vector<PerlIdiomParam> result;

            if (param.macro_name == "TSelf")
                return result;

            // TClass(wxString) -> wxString lifecycle
            if (param.macro_name == "TClass" && param.macro_arg == "wxString")
            {
                std::string name =
                    PerlEscapeName(param.param_name.empty() ? "str" : param.param_name);
                std::string ws = "_ws_" + name;
                result.push_back({
                    name,
                    "$" + ws,
                    "my $" + ws + " = kwxPerl::String::to_wx($" + name + ");",
                    "kwxPerl::String::delete_wx($" + ws + ");",
                });
                return result;
            }

            // TClass(other) / TClassRef -> extract pointer
            if (param.macro_name == "TClass" || param.macro_name == "TClassRef")
            {
                std::string name =
                    PerlEscapeName(param.param_name.empty() ? "obj" : param.param_name);
                result.push_back({
                    name,
                    "defined $" + name + " ? $" + name + "->{ptr} : undef",
                    "",
                    "",
                });
                return result;
            }

            // Geometry expansion: TPoint, TSize, TRect, TVector
            if (param.macro_name == "TPoint" || param.macro_name == "TSize" ||
                param.macro_name == "TRect" || param.macro_name == "TVector" ||
                param.macro_name == "TPointLong" || param.macro_name == "TSizeLong" ||
                param.macro_name == "TRectLong" || param.macro_name == "TVectorLong")
            {
                for (auto& n: PerlSplitMacroArg(param.macro_arg))
                {
                    std::string esc = PerlEscapeName(n);
                    result.push_back({ esc, "$" + esc, "", "" });
                }
                return result;
            }

            // Output geometry parameters -> pass-through
            if (param.macro_name == "TPointOut" || param.macro_name == "TSizeOut" ||
                param.macro_name == "TRectOut" || param.macro_name == "TVectorOut" ||
                param.macro_name == "TPointOutVoid" || param.macro_name == "TSizeOutVoid" ||
                param.macro_name == "TRectOutVoid" || param.macro_name == "TVectorOutVoid" ||
                param.macro_name == "TSizeOutDouble")
            {
                for (auto& n: PerlSplitMacroArg(param.macro_arg))
                {
                    std::string esc = PerlEscapeName(n);
                    result.push_back({ esc, "$" + esc, "", "" });
                }
                return result;
            }

            if (param.macro_name == "TColorRGB")
            {
                for (auto& n: PerlSplitMacroArg(param.macro_arg))
                {
                    std::string esc = PerlEscapeName(n);
                    result.push_back({ esc, "$" + esc, "", "" });
                }
                return result;
            }

            // Array types: count + pointer pass-through
            if (param.macro_name == "TArrayString" || param.macro_name == "TArrayInt" ||
                param.macro_name == "TByteString" || param.macro_name == "TByteStringLazy")
            {
                auto names = PerlSplitMacroArg(param.macro_arg);
                if (names.size() >= 2)
                {
                    result.push_back(
                        { PerlEscapeName(names[0]), "$" + PerlEscapeName(names[0]), "", "" });
                    result.push_back(
                        { PerlEscapeName(names[1]), "$" + PerlEscapeName(names[1]), "", "" });
                }
                return result;
            }

            if (param.macro_name == "TArrayObjectOutVoid")
            {
                std::string name =
                    PerlEscapeName(param.param_name.empty() ? "arr" : param.param_name);
                result.push_back({ name, "$" + name, "", "" });
                return result;
            }

            // TBool -> convert to int 0/1
            if (param.macro_name == "TBool" || param.raw_type == "TBool")
            {
                std::string name =
                    PerlEscapeName(param.param_name.empty() ? "flag" : param.param_name);
                result.push_back({ name, "$" + name + " ? 1 : 0", "", "" });
                return result;
            }

            // Pass-through for everything else
            std::string name = PerlEscapeName(param.param_name.empty() ? "arg" : param.param_name);
            result.push_back({ name, "$" + name, "", "" });
            return result;
        }

        // -----------------------------------------------------------------
        // OO Layer Helpers: constructor %args parameter conversion
        // -----------------------------------------------------------------

        struct PerlConstructorArg
        {
            std::string arg_key;    // Hash key: "parent", "id", etc.
            std::string call_expr;  // Expression for the FFI call
            std::string pre_call;   // Code before the call
            std::string post_call;  // Code after the call
        };

        // Default value for a constructor hash-arg based on type and name.
        std::string PerlArgDefault(const Param& p, const std::string& name)
        {
            if (p.macro_name == "TClass" && p.macro_arg == "wxString")
                return "''";
            if (p.raw_type == "TString")
                return "''";
            if (p.macro_name == "TClass" || p.macro_name == "TClassRef")
                return "";  // handled with defined check
            if (p.macro_name == "TBool" || p.raw_type == "TBool")
                return "0";
            if (name == "id")
                return "-1";
            if (name == "style" || name == "styles")
                return "0";
            if (name == "x" || name == "y" || name == "left" || name == "top")
                return "-1";
            if (name == "w" || name == "h" || name == "width" || name == "height")
                return "-1";
            return "0";
        }

        // Convert one Param to constructor %args entries.
        std::vector<PerlConstructorArg> ConvertToPerlCtorParam(const Param& param)
        {
            std::vector<PerlConstructorArg> result;

            if (param.macro_name == "TSelf")
                return result;

            // TClass(wxString) -> string lifecycle
            if (param.macro_name == "TClass" && param.macro_arg == "wxString")
            {
                std::string name =
                    PerlEscapeName(param.param_name.empty() ? "str" : param.param_name);
                std::string ws = "_ws_" + name;
                result.push_back({
                    name,
                    "$" + ws,
                    "my $" + ws + " = kwxPerl::String::to_wx($args{" + name + "} // '');",
                    "kwxPerl::String::delete_wx($" + ws + ");",
                });
                return result;
            }

            // TClass(other) / TClassRef -> extract pointer
            if (param.macro_name == "TClass" || param.macro_name == "TClassRef")
            {
                std::string name =
                    PerlEscapeName(param.param_name.empty() ? "obj" : param.param_name);
                result.push_back({
                    name,
                    "defined $args{" + name + "} ? $args{" + name + "}->{ptr} : undef",
                    "",
                    "",
                });
                return result;
            }

            // Geometry expansion
            if (param.macro_name == "TPoint" || param.macro_name == "TSize" ||
                param.macro_name == "TRect" || param.macro_name == "TVector" ||
                param.macro_name == "TPointLong" || param.macro_name == "TSizeLong" ||
                param.macro_name == "TRectLong" || param.macro_name == "TVectorLong")
            {
                for (auto& n: PerlSplitMacroArg(param.macro_arg))
                {
                    std::string esc = PerlEscapeName(n);
                    std::string def = PerlArgDefault(param, esc);
                    result.push_back({ esc, "$args{" + esc + "} // " + def, "", "" });
                }
                return result;
            }

            // Output geometry -> pass-through
            if (param.macro_name == "TPointOut" || param.macro_name == "TSizeOut" ||
                param.macro_name == "TRectOut" || param.macro_name == "TVectorOut" ||
                param.macro_name == "TPointOutVoid" || param.macro_name == "TSizeOutVoid" ||
                param.macro_name == "TRectOutVoid" || param.macro_name == "TVectorOutVoid" ||
                param.macro_name == "TSizeOutDouble")
            {
                for (auto& n: PerlSplitMacroArg(param.macro_arg))
                {
                    std::string esc = PerlEscapeName(n);
                    result.push_back({ esc, "$args{" + esc + "}", "", "" });
                }
                return result;
            }

            if (param.macro_name == "TColorRGB")
            {
                for (auto& n: PerlSplitMacroArg(param.macro_arg))
                {
                    std::string esc = PerlEscapeName(n);
                    result.push_back({ esc, "$args{" + esc + "} // 0", "", "" });
                }
                return result;
            }

            // Array types
            if (param.macro_name == "TArrayString" || param.macro_name == "TArrayInt" ||
                param.macro_name == "TByteString" || param.macro_name == "TByteStringLazy")
            {
                auto names = PerlSplitMacroArg(param.macro_arg);
                if (names.size() >= 2)
                {
                    result.push_back({ PerlEscapeName(names[0]),
                                       "$args{" + PerlEscapeName(names[0]) + "} // 0", "", "" });
                    result.push_back({ PerlEscapeName(names[1]),
                                       "$args{" + PerlEscapeName(names[1]) + "}", "", "" });
                }
                return result;
            }

            // TBool
            if (param.macro_name == "TBool" || param.raw_type == "TBool")
            {
                std::string name =
                    PerlEscapeName(param.param_name.empty() ? "flag" : param.param_name);
                result.push_back({ name, "$args{" + name + "} // 0", "", "" });
                return result;
            }

            // Plain type fallback
            std::string name = PerlEscapeName(param.param_name.empty() ? "arg" : param.param_name);
            std::string def = PerlArgDefault(param, name);
            result.push_back({ name, "$args{" + name + "} // " + def, "", "" });
            return result;
        }

        // Map constructor method_name to Perl sub name.
        std::string PerlCtorName(const FunctionDecl& func)
        {
            if (func.method_name == "Create")
                return "new";
            // "CreateEmpty" -> "new_empty"
            std::string suffix = func.method_name.substr(6);  // strip "Create"
            if (suffix.empty())
                return "new";
            return "new_" + ToSnakeCase(suffix);
        }

        // Count valid functions in a class (for diagnostics and skipping empty classes).
        size_t CountValidFunctions(const ClassInfo& cls)
        {
            size_t count = 0;
            for (const auto& f: cls.methods)
            {
                if (IsValidFunction(f))
                    ++count;
            }
            return count;
        }

        // Check if any method in a class uses wxString (input or output).
        bool ClassNeedsString(const ClassInfo& cls)
        {
            for (const auto& f: cls.methods)
            {
                if (!IsValidFunction(f))
                    continue;
                if (IsStringReturn(f))
                    return true;
                for (const auto& p: f.params)
                {
                    if (p.macro_name == "TClass" && p.macro_arg == "wxString")
                        return true;
                }
            }
            return false;
        }

    }  // anonymous namespace

    // =========================================================================
    // PerlEmitter public interface
    // =========================================================================

    void PerlEmitter::Generate(const ParsedFFI& ffi, const fs::path& outDir)
    {
        auto rawDir = outDir / "lib" / "wx" / "ffi" / "raw";
        auto ooDir = outDir / "lib" / "wx";
        fs::create_directories(rawDir);
        fs::create_directories(ooDir);

        GenerateRawClassFiles(ffi, rawDir);
        GenerateRawConstants(ffi, rawDir);
        GenerateRawFreeFunctions(ffi, rawDir);
        GenerateRawInit(ffi, rawDir);
        GenerateOOClasses(ffi, ooDir);

        std::cerr << "Perl: generated files in " << outDir << "\n";
    }

    VerifyResult PerlEmitter::Verify(const ParsedFFI& /* ffi */, const fs::path& /* dir */)
    {
        VerifyResult result;
        result.success = false;
        result.messages.push_back("Perl verify: use 'kwxgen verify' command instead");
        return result;
    }

    // =========================================================================
    // Layer 1: Raw FFI modules (lib/wx/ffi/raw/<Class>.pm)
    // =========================================================================

    void PerlEmitter::GenerateRawClassFiles(const ParsedFFI& ffi, const fs::path& rawDir)
    {
        static const std::unordered_set<std::string> kSkipClass = { "wxString" };

        size_t classCount = 0;
        size_t totalMethods = 0;

        for (const auto& cls: ffi.classes)
        {
            if (cls.methods.empty() || kSkipClass.count(cls.name))
                continue;
            size_t validCount = CountValidFunctions(cls);
            if (validCount == 0)
                continue;

            auto path = rawDir / PerlPMFileName(cls.name);
            ConditionalFileWriter out(path);

            std::string pkg = PerlRawPackageName(cls.name);

            WriteGeneratedHeader(out, "#", false);
            out << "package " << pkg << ";\n\n";
            out << "use strict;\n";
            out << "use warnings;\n\n";

            // Declare package variables
            out << "our (\n";
            bool firstVar = true;
            for (const auto& f: cls.methods)
            {
                if (!IsValidFunction(f))
                    continue;
                if (!firstVar)
                    out << ",\n";
                out << "    $" << CFuncName(f);
                firstVar = false;
            }
            out << "\n);\n\n";

            // _init sub
            out << "sub _init {\n";
            out << "    my ($ffi) = @_;\n\n";

            for (const auto& f: cls.methods)
            {
                if (!IsValidFunction(f))
                    continue;

                std::string funcName = CFuncName(f);
                std::string retType = PerlReturnType(f.return_type, f.return_macro);

                std::vector<PerlParam> pParams;
                for (const auto& p: f.params)
                {
                    auto expanded = ExpandParamToPerl(p);
                    for (auto& pp: expanded)
                        pParams.push_back(std::move(pp));
                }

                out << "    $" << funcName << " = $ffi->function(\n";
                out << "        " << funcName << " => [";
                for (size_t i = 0; i < pParams.size(); ++i)
                {
                    if (i > 0)
                        out << ", ";
                    out << "'" << pParams[i].platypus_type << "'";
                }
                out << "]\n";
                out << "        => '" << retType << "'\n";
                out << "    );\n\n";

                ++totalMethods;
            }

            out << "}\n\n";
            out << "1;\n";
            ++classCount;
        }

        std::cerr << "  raw/ class modules:         " << classCount << " classes, " << totalMethods
                  << " functions\n";
    }

    // =========================================================================
    // Layer 1: Raw Constants (lib/wx/ffi/raw/Constants.pm)
    // =========================================================================

    void PerlEmitter::GenerateRawConstants(const ParsedFFI& ffi, const fs::path& rawDir)
    {
        auto path = rawDir / "Constants.pm";
        ConditionalFileWriter out(path);

        WriteGeneratedHeader(out, "#", false);
        out << "package wx::FFI::Raw::Constants;\n\n";
        out << "use strict;\n";
        out << "use warnings;\n";
        out << "use Exporter 'import';\n\n";
        out << "our @EXPORT_OK;\n";
        out << "our %EXPORT_TAGS;\n";
        out << "my %constants;\n\n";

        out << "sub _init {\n";
        out << "    my ($ffi) = @_;\n\n";

        // Events
        auto sortedEvents = ffi.events;
        std::sort(sortedEvents.begin(), sortedEvents.end(),
                  [](const EventDecl& a, const EventDecl& b)
                  {
                      return a.event_name < b.event_name;
                  });

        out << "    # Events (" << sortedEvents.size() << ")\n";
        for (const auto& e: sortedEvents)
        {
            out << "    $constants{" << e.event_name << "} = $ffi->function(" << e.export_name
                << " => [] => 'int')->();\n";
        }
        out << "\n";

        // Keys
        auto sortedKeys = ffi.keys;
        std::sort(sortedKeys.begin(), sortedKeys.end(),
                  [](const KeyDecl& a, const KeyDecl& b)
                  {
                      return a.key_name < b.key_name;
                  });

        out << "    # Keys (" << sortedKeys.size() << ")\n";
        for (const auto& k: sortedKeys)
        {
            out << "    $constants{" << k.key_name << "} = $ffi->function(" << k.export_name
                << " => [] => 'int')->();\n";
        }
        out << "\n";

        // Constants (defs)
        auto sortedConstants = ffi.constants;
        std::sort(sortedConstants.begin(), sortedConstants.end(),
                  [](const ConstantDecl& a, const ConstantDecl& b)
                  {
                      return a.export_name < b.export_name;
                  });

        out << "    # Constants (" << sortedConstants.size() << ")\n";
        for (const auto& c: sortedConstants)
        {
            std::string retType = (c.return_type.find('*') != std::string::npos) ? "opaque" : "int";
            std::string constName = c.export_name.substr(3);
            out << "    $constants{" << constName << "} = $ffi->function(" << c.export_name
                << " => [] => '" << retType << "')->();\n";
        }
        out << "\n";

        // Create constant subs dynamically
        out << "    # Create constant subroutines\n";
        out << "    for my $name (sort keys %constants) {\n";
        out << "        no strict 'refs';\n";
        out << "        *{\"wx::FFI::Raw::Constants::$name\"} = sub () { "
               "$constants{$name} };\n";
        out << "        push @EXPORT_OK, $name;\n";
        out << "    }\n\n";

        // Build export tags
        out << "    # Build export tags\n";
        out << "    my @events = grep { /^EVT_/ } @EXPORT_OK;\n";
        out << "    my @keys_list = grep { /^K_/ } @EXPORT_OK;\n";
        out << "    my @consts = grep { !/^EVT_/ && !/^K_/ } @EXPORT_OK;\n";
        out << "    $EXPORT_TAGS{events} = \\@events;\n";
        out << "    $EXPORT_TAGS{keys} = \\@keys_list;\n";
        out << "    $EXPORT_TAGS{constants} = \\@consts;\n";
        out << "    $EXPORT_TAGS{all} = \\@EXPORT_OK;\n";
        out << "}\n\n";

        // Lookup helper
        out << "sub get {\n";
        out << "    my ($name) = @_;\n";
        out << "    return $constants{$name} if exists $constants{$name};\n";
        out << "    $name =~ s/^wx//;\n";
        out << "    return $constants{\"wx$name\"} // $constants{$name};\n";
        out << "}\n\n";

        out << "1;\n";

        std::cerr << "  raw/Constants.pm:           " << sortedEvents.size() << " events, "
                  << sortedKeys.size() << " keys, " << sortedConstants.size() << " constants\n";
    }

    // =========================================================================
    // Layer 1: Raw Free Functions (lib/wx/ffi/raw/Functions.pm)
    // =========================================================================

    void PerlEmitter::GenerateRawFreeFunctions(const ParsedFFI& ffi, const fs::path& rawDir)
    {
        if (ffi.free_functions.empty())
            return;

        auto path = rawDir / "Functions.pm";
        ConditionalFileWriter out(path);

        WriteGeneratedHeader(out, "#", false);
        out << "package wx::FFI::Raw::Functions;\n\n";
        out << "use strict;\n";
        out << "use warnings;\n\n";

        // Declare variables
        out << "our (\n";
        bool firstVar = true;
        for (const auto& f: ffi.free_functions)
        {
            if (!IsValidFunction(f))
                continue;
            if (!firstVar)
                out << ",\n";
            out << "    $" << CFuncName(f);
            firstVar = false;
        }
        out << "\n);\n\n";

        // _init sub
        out << "sub _init {\n";
        out << "    my ($ffi) = @_;\n\n";

        size_t count = 0;
        for (const auto& f: ffi.free_functions)
        {
            if (!IsValidFunction(f))
                continue;

            std::string funcName = CFuncName(f);
            std::string retType = PerlReturnType(f.return_type, f.return_macro);

            std::vector<PerlParam> pParams;
            for (const auto& p: f.params)
            {
                auto expanded = ExpandParamToPerl(p);
                for (auto& pp: expanded)
                    pParams.push_back(std::move(pp));
            }

            out << "    $" << funcName << " = $ffi->function(\n";
            out << "        " << funcName << " => [";
            for (size_t i = 0; i < pParams.size(); ++i)
            {
                if (i > 0)
                    out << ", ";
                out << "'" << pParams[i].platypus_type << "'";
            }
            out << "]\n";
            out << "        => '" << retType << "'\n";
            out << "    );\n\n";

            ++count;
        }

        out << "}\n\n";
        out << "1;\n";

        std::cerr << "  raw/Functions.pm:           " << count << " free functions\n";
    }

    // =========================================================================
    // Layer 1: Master Init (lib/wx/ffi/raw/Init.pm)
    // =========================================================================

    void PerlEmitter::GenerateRawInit(const ParsedFFI& ffi, const fs::path& rawDir)
    {
        static const std::unordered_set<std::string> kSkipClass = { "wxString" };

        auto path = rawDir / "Init.pm";
        ConditionalFileWriter out(path);

        WriteGeneratedHeader(out, "#", false);
        out << "package wx::FFI::Raw::Init;\n\n";
        out << "use strict;\n";
        out << "use warnings;\n\n";

        // Collect and sort class names
        std::vector<std::string> classNames;
        for (const auto& cls: ffi.classes)
        {
            if (cls.methods.empty() || kSkipClass.count(cls.name))
                continue;
            if (CountValidFunctions(cls) == 0)
                continue;
            classNames.push_back(cls.name);
        }
        std::sort(classNames.begin(), classNames.end());

        // use statements
        out << "use wx::FFI::Raw::Constants;\n";
        for (const auto& name: classNames)
            out << "use " << PerlRawPackageName(name) << ";\n";
        if (!ffi.free_functions.empty())
            out << "use wx::FFI::Raw::Functions;\n";
        out << "\n";

        // init_all sub
        out << "sub init_all {\n";
        out << "    my ($ffi) = @_;\n\n";
        out << "    wx::FFI::Raw::Constants::_init($ffi);\n";
        for (const auto& name: classNames)
            out << "    " << PerlRawPackageName(name) << "::_init($ffi);\n";
        if (!ffi.free_functions.empty())
            out << "    wx::FFI::Raw::Functions::_init($ffi);\n";

        out << "}\n\n";
        out << "1;\n";

        std::cerr << "  raw/Init.pm:                master init (" << classNames.size()
                  << " modules)\n";
    }

    // =========================================================================
    // Layer 2: OO wrapper modules (lib/wx/<Class>.pm)
    // =========================================================================

    void PerlEmitter::GenerateOOClasses(const ParsedFFI& ffi, const fs::path& ooDir)
    {
        static const std::unordered_set<std::string> kSkipClass = { "wxString" };

        size_t classCount = 0;
        size_t methodCount = 0;

        for (const auto& cls: ffi.classes)
        {
            if (cls.methods.empty() || kSkipClass.count(cls.name))
                continue;
            if (CountValidFunctions(cls) == 0)
                continue;

            auto path = ooDir / PerlPMFileName(cls.name);
            ConditionalFileWriter out(path);

            EmitOOClassFile(out, cls, ffi);
            ++classCount;

            for (const auto& f: cls.methods)
            {
                if (IsValidFunction(f))
                    ++methodCount;
            }
        }

        std::cerr << "  wx/ OO modules:             " << classCount << " classes, " << methodCount
                  << " methods\n";
    }

    void PerlEmitter::EmitOOClassFile(std::ostream& out, const ClassInfo& cls, const ParsedFFI& ffi)
    {
        std::string ooPkg = PerlOOPackageName(cls.name);
        std::string rawPkg = PerlRawPackageName(cls.name);

        // Build the set of wrapped classes for parent resolution.
        std::unordered_set<std::string> wrappedClasses;
        for (const auto& other: ffi.classes)
        {
            if (!other.methods.empty() && other.name != "wxString")
                wrappedClasses.insert(other.name);
        }

        std::string parentClass = FindWrappedParent(cls.name, ffi, wrappedClasses);

        // Check for mixins
        std::vector<std::string> mixinParents;
        auto mixin_it = ffi.mixin_map.find(cls.name);
        if (mixin_it != ffi.mixin_map.end())
        {
            for (const auto& m: mixin_it->second)
            {
                if (wrappedClasses.count(m))
                    mixinParents.push_back(m);
            }
        }

        bool needsString = ClassNeedsString(cls);

        // --- Header ---
        WriteGeneratedHeader(out, "#", false);
        out << "package " << ooPkg << ";\n\n";
        out << "use strict;\n";
        out << "use warnings;\n";

        // Inheritance: primary parent + mixins
        if (!parentClass.empty() || !mixinParents.empty())
        {
            out << "use parent qw(";
            bool first = true;
            if (!parentClass.empty())
            {
                out << PerlOOPackageName(parentClass);
                first = false;
            }
            for (const auto& m: mixinParents)
            {
                if (!first)
                    out << " ";
                out << PerlOOPackageName(m);
                first = false;
            }
            out << ");\n";
        }

        out << "use " << rawPkg << ";\n";
        if (needsString)
            out << "use kwxPerl::String;\n";
        out << "\n";

        // --- Pointer accessor ---
        out << "sub ptr { return $_[0]->{ptr} }\n\n";

        // --- Constructors ---
        for (const auto& func: cls.methods)
        {
            if (!IsValidFunction(func))
                continue;
            if (!func.is_constructor || func.has_self)
                continue;

            std::string methodName = PerlCtorName(func);

            // Build constructor arg groups
            std::vector<std::vector<PerlConstructorArg>> argGroups;
            for (const auto& param: func.params)
            {
                if (param.macro_name == "TSelf")
                    continue;
                argGroups.push_back(ConvertToPerlCtorParam(param));
            }

            out << "sub " << methodName << " {\n";
            out << "    my ($class, %args) = @_;\n";

            // Pre-call statements
            for (const auto& group: argGroups)
            {
                for (const auto& arg: group)
                {
                    if (!arg.pre_call.empty())
                        out << "    " << arg.pre_call << "\n";
                }
            }

            // C call
            out << "    my $ptr = $" << rawPkg << "::" << CFuncName(func) << "->(\n";
            bool firstArg = true;
            for (const auto& group: argGroups)
            {
                for (const auto& arg: group)
                {
                    if (!firstArg)
                        out << ",\n";
                    out << "        " << arg.call_expr;
                    firstArg = false;
                }
            }
            out << "\n    );\n";

            // Post-call cleanup
            for (const auto& group: argGroups)
            {
                for (const auto& arg: group)
                {
                    if (!arg.post_call.empty())
                        out << "    " << arg.post_call << "\n";
                }
            }

            out << "    return undef unless defined $ptr;\n";
            out << "    return bless { ptr => $ptr }, $class;\n";
            out << "}\n\n";
        }

        // --- Methods (non-constructor, non-destructor) ---
        for (const auto& func: cls.methods)
        {
            if (!IsValidFunction(func))
                continue;
            if (func.is_constructor && !func.has_self)
                continue;
            if (func.is_destructor)
                continue;

            bool isVoid = IsVoidReturn(func.return_type);
            bool isStringRet = IsStringReturn(func);
            bool isBoolRet = IsBoolReturn(func);
            bool isClassRet = IsClassReturn(func);
            bool pseudoSelf = HasPseudoSelf(func);

            std::string methodName = ToSnakeCase(func.method_name);

            // Build param list (skip self/pseudo-self)
            std::vector<std::vector<PerlIdiomParam>> paramGroups;
            bool hasPostCalls = false;
            for (size_t pi = 0; pi < func.params.size(); ++pi)
            {
                const auto& param = func.params[pi];
                if (param.macro_name == "TSelf")
                    continue;
                if (pseudoSelf && pi == 0)
                    continue;
                auto group = ConvertToPerlMethodParam(param);
                for (const auto& lp: group)
                {
                    if (!lp.post_call.empty())
                        hasPostCalls = true;
                }
                paramGroups.push_back(std::move(group));
            }

            // Method signature
            out << "sub " << methodName << " {\n";
            out << "    my ($self";
            for (const auto& group: paramGroups)
            {
                for (const auto& lp: group)
                    out << ", $" << lp.name;
            }
            out << ") = @_;\n";

            // Pre-call statements
            for (const auto& group: paramGroups)
            {
                for (const auto& lp: group)
                {
                    if (!lp.pre_call.empty())
                        out << "    " << lp.pre_call << "\n";
                }
            }

            // Build call expression
            std::string callArgs = "$self->{ptr}";
            for (const auto& group: paramGroups)
            {
                for (const auto& lp: group)
                    callArgs += ", " + lp.call_expr;
            }

            std::string call = "$" + rawPkg + "::" + CFuncName(func) + "->" + "(" + callArgs + ")";

            // Emit call + return
            if (isVoid)
            {
                out << "    " << call << ";\n";
                for (const auto& group: paramGroups)
                {
                    for (const auto& lp: group)
                    {
                        if (!lp.post_call.empty())
                            out << "    " << lp.post_call << "\n";
                    }
                }
            }
            else if (hasPostCalls)
            {
                // Capture result, cleanup, then return.
                if (isStringRet)
                    out << "    my $_result = kwxPerl::String::from_wx_and_delete(" << call
                        << ");\n";
                else if (isBoolRet)
                    out << "    my $_result = " << call << " ? 1 : 0;\n";
                else
                    out << "    my $_result = " << call << ";\n";

                for (const auto& group: paramGroups)
                {
                    for (const auto& lp: group)
                    {
                        if (!lp.post_call.empty())
                            out << "    " << lp.post_call << "\n";
                    }
                }
                out << "    return $_result;\n";
            }
            else
            {
                if (isStringRet)
                {
                    out << "    return kwxPerl::String::from_wx_and_delete(" << call << ");\n";
                }
                else if (isBoolRet)
                {
                    out << "    return " << call << " ? 1 : 0;\n";
                }
                else if (isClassRet)
                {
                    std::string retPkg = PerlOOPackageName(func.return_arg);
                    out << "    my $_ptr = " << call << ";\n";
                    out << "    return defined $_ptr ? bless({ ptr => $_ptr }, '" << retPkg
                        << "') : undef;\n";
                }
                else
                {
                    out << "    return " << call << ";\n";
                }
            }

            out << "}\n\n";
        }

        // --- Destructor ---
        for (const auto& func: cls.methods)
        {
            if (!IsValidFunction(func) || !func.is_destructor)
                continue;

            bool hasNonSelfParams = false;
            for (const auto& param: func.params)
            {
                if (param.macro_name != "TSelf")
                    hasNonSelfParams = true;
            }

            if (hasNonSelfParams)
            {
                // Not a true destructor: emit as a regular method.
                std::vector<std::vector<PerlIdiomParam>> paramGroups;
                for (const auto& param: func.params)
                {
                    if (param.macro_name == "TSelf")
                        continue;
                    paramGroups.push_back(ConvertToPerlMethodParam(param));
                }

                out << "sub " << ToSnakeCase(func.method_name) << " {\n";
                out << "    my ($self";
                for (const auto& group: paramGroups)
                {
                    for (const auto& lp: group)
                        out << ", $" << lp.name;
                }
                out << ") = @_;\n";

                std::string callArgs = "$self->{ptr}";
                for (const auto& group: paramGroups)
                {
                    for (const auto& lp: group)
                        callArgs += ", " + lp.call_expr;
                }

                if (IsVoidReturn(func.return_type))
                {
                    out << "    $" << rawPkg << "::" << CFuncName(func) << "->" << "(" << callArgs
                        << ");\n";
                }
                else
                {
                    out << "    return $" << rawPkg << "::" << CFuncName(func) << "->" << "("
                        << callArgs << ");\n";
                }
                out << "}\n\n";
            }
            else
            {
                // True destructor: guard against double-delete.
                out << "sub delete {\n";
                out << "    my ($self) = @_;\n";
                out << "    if (defined $self->{ptr}) {\n";
                out << "        $" << rawPkg << "::" << CFuncName(func) << "->" << "("
                    << "$self->{ptr});\n";
                out << "        $self->{ptr} = undef;\n";
                out << "    }\n";
                out << "}\n\n";
            }
        }

        // --- Event connect convenience (only for wxWindow) ---
        if (cls.name == "wxWindow")
        {
            out << "sub connect {\n";
            out << "    my ($self, $event_type, $callback, %opts) = @_;\n";
            out << "    kwxPerl::Event::connect(\n";
            out << "        $self->{ptr},\n";
            out << "        $opts{id}      // -1,\n";
            out << "        $opts{last_id} // -1,\n";
            out << "        $event_type,\n";
            out << "        $callback,\n";
            out << "    );\n";
            out << "}\n\n";
        }

        out << "1;\n";
    }

}  // namespace kwxgen
