// Generated by GitHub Copilot. Directed and reviewed by Ralph Walden.
// Licensed under Apache 2.0. This file is not subject to copyright.

#include "lang_luajit.h"

#include "../file_writer.h"
#include "lang_common.h"
#include "luajit_type_map.h"
#include <algorithm>
#include <cctype>
#include <filesystem>
#include <iostream>
#include <set>
#include <unordered_set>
#include <vector>

namespace fs = std::filesystem;

namespace kwxgen
{

    namespace
    {

        // Emit a single C function declaration for ffi.cdef.
        void EmitCDecl(std::ostream& out, const std::string& returnType,
                       const std::string& funcName, const std::vector<LuaCParam>& params)
        {
            out << "    " << returnType << " " << funcName << "(";
            for (size_t idx = 0; idx < params.size(); ++idx)
            {
                if (idx > 0)
                    out << ", ";
                out << params[idx].c_type << " " << params[idx].name;
            }
            out << ");\n";
        }

        // Emit a C declaration from a FunctionDecl.
        void EmitFunctionCDecl(std::ostream& out, const FunctionDecl& func)
        {
            std::string ret_type = LuaJITReturnType(func.return_type, func.return_macro);
            std::string func_name = CFuncName(func);

            std::vector<LuaCParam> c_params;
            for (const auto& param: func.params)
            {
                auto expanded = ExpandParamToC(param);
                for (auto& cp: expanded)
                {
                    cp.name = LuaEscapeName(cp.name);
                    c_params.push_back(std::move(cp));
                }
            }

            EmitCDecl(out, ret_type, func_name, c_params);
        }

        // -----------------------------------------------------------------
        // Idiomatic layer helpers
        // -----------------------------------------------------------------

        // A single idiomatic Lua parameter and its call expression.
        struct LuaIdiomParam
        {
            std::string name;       // Lua parameter name in function signature
            std::string call_expr;  // Expression passed to the C call
            std::string pre_call;   // Statement before the call (empty if none)
            std::string post_call;  // Statement after the call (empty if none)
        };

        // Output filename for a class: "wxButton" -> "wxbutton_gen.lua"
        auto LuaClassFileName(const std::string& class_name) -> std::string
        {
            std::string result;
            for (char ch: class_name)
            {
                result += static_cast<char>(std::tolower(static_cast<unsigned char>(ch)));
            }
            return result + "_gen.lua";
        }

        // True if the function return type is void.
        [[nodiscard]] auto IsVoidReturn(const std::string& return_type) -> bool
        {
            return return_type.empty() || return_type == "void";
        }

        // True if the return is a string type that needs wxString->Lua conversion.
        [[nodiscard]] auto IsStringReturn(const FunctionDecl& func) -> bool
        {
            if (func.return_type == "TString" || func.return_type == "TStringOut")
                return true;
            if (func.return_macro == "TClass" && func.return_arg == "wxString")
                return true;
            return false;
        }

        // True if the return is a boolean type.
        [[nodiscard]] auto IsBoolReturn(const FunctionDecl& func) -> bool
        {
            return func.return_type == "TBool" || func.return_type == "TBoolInt";
        }

        // Build a Lua return expression wrapping a raw C call result.
        auto LuaReturnExpr(const FunctionDecl& func, const std::string& call) -> std::string
        {
            if (IsBoolReturn(func))
                return "_H.to_bool(" + call + ")";
            if (IsStringReturn(func))
                return "_H.wxs_to_str(" + call + ")";
            // Everything else (int, double, pointer, void): pass through.
            return call;
        }

        // Convert one Param into zero or more idiomatic Lua parameters.
        auto ConvertToLuaIdiomParams(const Param& param, bool in_constructor)
            -> std::vector<LuaIdiomParam>
        {
            std::vector<LuaIdiomParam> result;

            // Self param -> handled by method receiver (self._ptr); skip.
            if (param.macro_name == "TSelf")
                return result;

            // Geometry expansion macros -> multiple numeric params.
            if (param.macro_name == "TPoint" || param.macro_name == "TSize" ||
                param.macro_name == "TRect" || param.macro_name == "TVector")
            {
                for (auto& name: LuaJITSplitMacroArg(param.macro_arg))
                {
                    std::string esc = LuaEscapeName(name);
                    result.push_back({ esc, esc, "", "" });
                }
                return result;
            }

            if (param.macro_name == "TPointLong" || param.macro_name == "TSizeLong" ||
                param.macro_name == "TRectLong" || param.macro_name == "TVectorLong")
            {
                for (auto& name: LuaJITSplitMacroArg(param.macro_arg))
                {
                    std::string esc = LuaEscapeName(name);
                    result.push_back({ esc, esc, "", "" });
                }
                return result;
            }

            // Output geometry parameters -> pointer params (pass-through).
            if (param.macro_name == "TPointOut" || param.macro_name == "TSizeOut" ||
                param.macro_name == "TRectOut" || param.macro_name == "TVectorOut" ||
                param.macro_name == "TPointOutVoid" || param.macro_name == "TSizeOutVoid" ||
                param.macro_name == "TRectOutVoid" || param.macro_name == "TVectorOutVoid")
            {
                for (auto& name: LuaJITSplitMacroArg(param.macro_arg))
                {
                    std::string esc = LuaEscapeName(name);
                    result.push_back({ esc, esc, "", "" });
                }
                return result;
            }

            if (param.macro_name == "TSizeOutDouble")
            {
                for (auto& name: LuaJITSplitMacroArg(param.macro_arg))
                {
                    std::string esc = LuaEscapeName(name);
                    result.push_back({ esc, esc, "", "" });
                }
                return result;
            }

            if (param.macro_name == "TColorRGB")
            {
                for (auto& name: LuaJITSplitMacroArg(param.macro_arg))
                {
                    std::string esc = LuaEscapeName(name);
                    result.push_back({ esc, esc, "", "" });
                }
                return result;
            }

            // Array types: count + pointer.
            if (param.macro_name == "TArrayString" || param.macro_name == "TArrayInt" ||
                param.macro_name == "TByteString" || param.macro_name == "TByteStringLazy")
            {
                auto names = LuaJITSplitMacroArg(param.macro_arg);
                if (names.size() >= 2)
                {
                    result.push_back({ LuaEscapeName(names[0]), LuaEscapeName(names[0]), "", "" });
                    result.push_back({ LuaEscapeName(names[1]), LuaEscapeName(names[1]), "", "" });
                }
                return result;
            }

            if (param.macro_name == "TArrayObjectOutVoid")
            {
                std::string name =
                    LuaEscapeName(param.param_name.empty() ? "arr" : param.param_name);
                result.push_back({ name, name, "", "" });
                return result;
            }

            // TClass(wxString) -> String input: create wxString, pass, free.
            if (param.macro_name == "TClass" && param.macro_arg == "wxString")
            {
                std::string name =
                    LuaEscapeName(param.param_name.empty() ? "str" : param.param_name);
                std::string ws_var = "_ws_" + name;
                result.push_back({
                    name,
                    ws_var,
                    "local " + ws_var + " = _H.wxs(" + name + ")",
                    "_H.wxs_free(" + ws_var + ")",
                });
                return result;
            }

            // TClass(other) -> Pointer: extract ._ptr via helper.
            if (param.macro_name == "TClass" || param.macro_name == "TClassRef")
            {
                std::string name =
                    LuaEscapeName(param.param_name.empty() ? "arg" : param.param_name);
                if (in_constructor && name == "parent")
                {
                    // Nullable parent window.
                    result.push_back({ "parent", "_H.ptr(parent)", "", "" });
                }
                else
                {
                    result.push_back({ name, "_H.ptr(" + name + ")", "", "" });
                }
                return result;
            }

            // TString (char*) input -> Lua string passes directly via LuaJIT FFI.
            if (param.raw_type == "TString" || param.macro_name == "TString")
            {
                std::string name =
                    LuaEscapeName(param.param_name.empty() ? "str" : param.param_name);
                result.push_back({ name, name, "", "" });
                return result;
            }

            // TStringVoid -> void* pass-through.
            if (param.raw_type == "TStringVoid" || param.macro_name == "TStringVoid")
            {
                std::string name =
                    LuaEscapeName(param.param_name.empty() ? "str" : param.param_name);
                result.push_back({ name, name, "", "" });
                return result;
            }

            // TStringOut -> output buffer pass-through.
            if (param.raw_type == "TStringOut")
            {
                std::string name =
                    LuaEscapeName(param.param_name.empty() ? "buf" : param.param_name);
                result.push_back({ name, name, "", "" });
                return result;
            }

            // TBool -> boolean to int conversion.
            if (param.macro_name == "TBool" || param.raw_type == "TBool")
            {
                std::string name =
                    LuaEscapeName(param.param_name.empty() ? "flag" : param.param_name);
                result.push_back({ name, "_H.from_bool(" + name + ")", "", "" });
                return result;
            }

            if (param.raw_type == "TBoolInt")
            {
                std::string name =
                    LuaEscapeName(param.param_name.empty() ? "flag" : param.param_name);
                result.push_back({ name, name, "", "" });
                return result;
            }

            if (param.raw_type == "TBool*")
            {
                std::string name =
                    LuaEscapeName(param.param_name.empty() ? "flag" : param.param_name);
                result.push_back({ name, name, "", "" });
                return result;
            }

            // Closure/callback function pointer.
            if (param.macro_name == "TClosureFun" || param.raw_type == "TClosureFun")
            {
                std::string name =
                    LuaEscapeName(param.param_name.empty() ? "fn" : param.param_name);
                result.push_back({ name, name, "", "" });
                return result;
            }

            // Opaque output arrays -> pass-through.
            if (param.raw_type == "TArrayIntOutVoid" || param.raw_type == "TArrayIntPtrOutVoid" ||
                param.raw_type == "TArrayStringOutVoid" || param.raw_type == "TByteStringOut" ||
                param.raw_type == "TByteStringLazyOut" || param.raw_type == "TArrayObjectOutVoid")
            {
                std::string name =
                    LuaEscapeName(param.param_name.empty() ? "arr" : param.param_name);
                result.push_back({ name, name, "", "" });
                return result;
            }

            // Plain C types -> pass through.
            std::string name = LuaEscapeName(param.param_name.empty() ? "arg" : param.param_name);
            result.push_back({ name, name, "", "" });
            return result;
        }

        // Find the parent class name that is actually wrapped (has methods).
        // Walk the hierarchy until we find a parent that exists in the classes list,
        // or return empty string if none found.
        auto FindWrappedParent(const std::string& class_name, const ParsedFFI& ffi,
                               const std::unordered_set<std::string>& wrapped_classes)
            -> std::string
        {
            auto iter = ffi.parent_map.find(class_name);
            std::set<std::string> visited;
            while (iter != ffi.parent_map.end())
            {
                const auto& parent = iter->second;
                if (visited.count(parent))
                    break;  // cycle guard
                visited.insert(parent);
                if (wrapped_classes.count(parent))
                    return parent;
                iter = ffi.parent_map.find(parent);
            }
            return "";
        }

    }  // anonymous namespace

    // -------------------------------------------------------------------------
    // LuaJITEmitter public interface
    // -------------------------------------------------------------------------

    void LuaJITEmitter::Generate(const ParsedFFI& ffi, const fs::path& outDir)
    {
        fs::create_directories(outDir);

        // Raw FFI layer
        GenerateEvents(ffi, outDir);
        GenerateKeys(ffi, outDir);
        GenerateConstants(ffi, outDir);
        GenerateClasses(ffi, outDir);
        GenerateFreeFunctions(ffi, outDir);
        GenerateInit(outDir, ffi.lib_name);

        // Idiomatic layer
        GenerateHelpers(outDir);
        GenerateIdiomaticClasses(ffi, outDir);

        std::cerr << "LuaJIT: generated files in " << outDir << "\n";
    }

    VerifyResult LuaJITEmitter::Verify(const ParsedFFI& /* ffi */, const fs::path& /* dir */)
    {
        VerifyResult result;
        result.success = false;
        result.messages.push_back("LuaJIT verify: use 'kwxgen verify' command instead");
        return result;
    }

    // -------------------------------------------------------------------------
    // kwxffi_events_gen.lua
    // -------------------------------------------------------------------------

    void LuaJITEmitter::GenerateEvents(const ParsedFFI& ffi, const fs::path& outDir)
    {
        auto path = outDir / "kwxffi_events_gen.lua";
        ConditionalFileWriter out(path);
        if (!out.is_open())
        {
            std::cerr << "Error: cannot create " << path << "\n";
            return;
        }

        WriteGeneratedHeader(out, "--", false);
        out << "local ffi = require(\"ffi\")\n\n";
        out << "ffi.cdef[[\n";

        auto sorted = ffi.events;
        std::sort(sorted.begin(), sorted.end(),
                  [](const EventDecl& lhs, const EventDecl& rhs)
                  {
                      return lhs.event_name < rhs.event_name;
                  });

        for (const auto& evt: sorted)
        {
            out << "    int " << evt.export_name << "();\n";
        }

        out << "]]\n";

        std::cerr << "  kwxffi_events_gen.lua:       " << ffi.events.size() << " events\n";
    }

    // -------------------------------------------------------------------------
    // kwxffi_keys_gen.lua
    // -------------------------------------------------------------------------

    void LuaJITEmitter::GenerateKeys(const ParsedFFI& ffi, const fs::path& outDir)
    {
        auto path = outDir / "kwxffi_keys_gen.lua";
        ConditionalFileWriter out(path);
        if (!out.is_open())
        {
            std::cerr << "Error: cannot create " << path << "\n";
            return;
        }

        WriteGeneratedHeader(out, "--", false);
        out << "local ffi = require(\"ffi\")\n\n";
        out << "ffi.cdef[[\n";

        auto sorted = ffi.keys;
        std::sort(sorted.begin(), sorted.end(),
                  [](const KeyDecl& lhs, const KeyDecl& rhs)
                  {
                      return lhs.key_name < rhs.key_name;
                  });

        for (const auto& key: sorted)
        {
            out << "    int " << key.export_name << "();\n";
        }

        out << "]]\n";

        std::cerr << "  kwxffi_keys_gen.lua:         " << ffi.keys.size() << " keys\n";
    }

    // -------------------------------------------------------------------------
    // kwxffi_constants_gen.lua
    // -------------------------------------------------------------------------

    void LuaJITEmitter::GenerateConstants(const ParsedFFI& ffi, const fs::path& outDir)
    {
        auto path = outDir / "kwxffi_constants_gen.lua";
        ConditionalFileWriter out(path);
        if (!out.is_open())
        {
            std::cerr << "Error: cannot create " << path << "\n";
            return;
        }

        WriteGeneratedHeader(out, "--", false);
        out << "local ffi = require(\"ffi\")\n\n";
        out << "ffi.cdef[[\n";

        auto sorted = ffi.constants;
        std::sort(sorted.begin(), sorted.end(),
                  [](const ConstantDecl& lhs, const ConstantDecl& rhs)
                  {
                      return lhs.export_name < rhs.export_name;
                  });

        for (const auto& cst: sorted)
        {
            std::string ret_type =
                (cst.return_type.find('*') != std::string::npos) ? "void*" : cst.return_type;
            out << "    " << ret_type << " " << cst.export_name << "();\n";
        }

        out << "]]\n";

        std::cerr << "  kwxffi_constants_gen.lua:    " << ffi.constants.size() << " constants\n";
    }

    // -------------------------------------------------------------------------
    // kwxffi_classes_gen.lua
    // -------------------------------------------------------------------------

    void LuaJITEmitter::GenerateClasses(const ParsedFFI& ffi, const fs::path& outDir)
    {
        auto path = outDir / "kwxffi_classes_gen.lua";
        ConditionalFileWriter out(path);
        if (!out.is_open())
        {
            std::cerr << "Error: cannot create " << path << "\n";
            return;
        }

        WriteGeneratedHeader(out, "--", false);
        out << "local ffi = require(\"ffi\")\n\n";

        size_t method_count = 0;
        size_t skipped_count = 0;

        for (const auto& cls: ffi.classes)
        {
            if (cls.methods.empty())
                continue;

            out << "-- " << cls.name << "\n";
            out << "ffi.cdef[[\n";

            for (const auto& func: cls.methods)
            {
                if (!IsValidFunction(func))
                {
                    ++skipped_count;
                    continue;
                }
                EmitFunctionCDecl(out, func);
                ++method_count;
            }

            out << "]]\n\n";
        }

        std::cerr << "  kwxffi_classes_gen.lua:      " << method_count << " methods";
        if (skipped_count > 0)
            std::cerr << " (" << skipped_count << " skipped)";
        std::cerr << "\n";
    }

    // -------------------------------------------------------------------------
    // kwxffi_freefuncs_gen.lua
    // -------------------------------------------------------------------------

    void LuaJITEmitter::GenerateFreeFunctions(const ParsedFFI& ffi, const fs::path& outDir)
    {
        if (ffi.free_functions.empty())
            return;

        auto path = outDir / "kwxffi_freefuncs_gen.lua";
        ConditionalFileWriter out(path);
        if (!out.is_open())
        {
            std::cerr << "Error: cannot create " << path << "\n";
            return;
        }

        WriteGeneratedHeader(out, "--", false);
        out << "local ffi = require(\"ffi\")\n\n";
        out << "ffi.cdef[[\n";

        size_t count = 0;
        for (const auto& func: ffi.free_functions)
        {
            if (!IsValidFunction(func))
                continue;
            EmitFunctionCDecl(out, func);
            ++count;
        }

        out << "]]\n";

        std::cerr << "  kwxffi_freefuncs_gen.lua:    " << count << " free functions\n";
    }

    // -------------------------------------------------------------------------
    // kwxffi_gen.lua -- main entry point, loads all sub-files and returns lib
    // -------------------------------------------------------------------------

    void LuaJITEmitter::GenerateInit(const fs::path& outDir, const std::string& libName)
    {
        auto path = outDir / "kwxffi_gen.lua";
        ConditionalFileWriter out(path);
        if (!out.is_open())
        {
            std::cerr << "Error: cannot create " << path << "\n";
            return;
        }

        WriteGeneratedHeader(out, "--", false);
        out << "-- Main entry point for kwxFFI LuaJIT bindings.\n";
        out << "-- Usage: local C = require(\"kwxffi_gen\")\n";
        out << "--        C.wxButton_Create(parent, id, label, x, y, w, h, style)\n";
        out << "\n";
        out << "require(\"kwxffi_events_gen\")\n";
        out << "require(\"kwxffi_keys_gen\")\n";
        out << "require(\"kwxffi_constants_gen\")\n";
        out << "require(\"kwxffi_classes_gen\")\n";
        out << "require(\"kwxffi_freefuncs_gen\")\n";
        out << "\n";
        out << "return require(\"ffi\").load(\"" << libName << "\")\n";

        std::cerr << "  kwxffi_gen.lua:              main entry point\n";
    }

    // =========================================================================
    // Idiomatic layer
    // =========================================================================

    // -------------------------------------------------------------------------
    // kwxffi_helpers_gen.lua -- utility functions for idiomatic wrappers
    // -------------------------------------------------------------------------

    void LuaJITEmitter::GenerateHelpers(const fs::path& outDir)
    {
        auto path = outDir / "kwxffi_helpers_gen.lua";
        ConditionalFileWriter out(path);
        if (!out.is_open())
        {
            std::cerr << "Error: cannot create " << path << "\n";
            return;
        }

        WriteGeneratedHeader(out, "--", false);
        out << "-- Helper utilities for idiomatic LuaJIT wrappers.\n";
        out << "-- Required by all generated class modules.\n";
        out << "\n";
        out << "local ffi = require(\"ffi\")\n";
        out << "local C = require(\"kwxffi_gen\")\n";
        out << "\n";
        out << "local M = {}\n";
        out << "\n";

        // wxString bridge
        out << "--- Create a wxString from a Lua string.\n";
        out << "--- @param str string|nil\n";
        out << "--- @return cdata|nil wxString pointer\n";
        out << "function M.wxs(str)\n";
        out << "    if str == nil then return nil end\n";
        out << "    return C.wxString_CreateUTF8(str)\n";
        out << "end\n";
        out << "\n";

        out << "--- Free a wxString.\n";
        out << "--- @param ws cdata|nil\n";
        out << "function M.wxs_free(ws)\n";
        out << "    if ws ~= nil then\n";
        out << "        C.wxString_Delete(ws)\n";
        out << "    end\n";
        out << "end\n";
        out << "\n";

        out << "--- Convert a wxString pointer to a Lua string, then free the wxString.\n";
        out << "--- @param ws_ptr cdata wxString pointer returned by a C wrapper\n";
        out << "--- @return string\n";
        out << "function M.wxs_to_str(ws_ptr)\n";
        out << "    if ws_ptr == nil then return \"\" end\n";
        out << "    local buf = C.kwxUtf8Buffer_Create(ws_ptr)\n";
        out << "    local str = ffi.string(C.kwxUtf8Buffer_Data(buf))\n";
        out << "    C.kwxUtf8Buffer_Delete(buf)\n";
        out << "    C.wxString_Delete(ws_ptr)\n";
        out << "    return str\n";
        out << "end\n";
        out << "\n";

        // Pointer extraction
        out << "--- Extract the C pointer from a wrapper object (or pass through cdata/nil).\n";
        out << "--- @param obj table|cdata|nil\n";
        out << "--- @return cdata pointer (or nil)\n";
        out << "function M.ptr(obj)\n";
        out << "    if obj == nil then return nil end\n";
        out << "    if type(obj) == \"cdata\" then return obj end\n";
        out << "    return obj._ptr\n";
        out << "end\n";
        out << "\n";

        // Boolean conversion
        out << "--- Convert a C int to a Lua boolean.\n";
        out << "--- @param val number\n";
        out << "--- @return boolean\n";
        out << "function M.to_bool(val) return val ~= 0 end\n";
        out << "\n";

        out << "--- Convert a Lua boolean to C int (1 or 0).\n";
        out << "--- @param val boolean\n";
        out << "--- @return number\n";
        out << "function M.from_bool(val) return val and 1 or 0 end\n";
        out << "\n";

        out << "return M\n";

        std::cerr << "  kwxffi_helpers_gen.lua:      helper utilities\n";
    }

    // -------------------------------------------------------------------------
    // Per-class idiomatic files + master include
    // -------------------------------------------------------------------------

    void LuaJITEmitter::EmitIdiomaticClassFile(std::ostream& out, const ClassInfo& cls,
                                               const ParsedFFI& ffi)
    {
        WriteGeneratedHeader(out, "--", false);
        out << "local ffi = require(\"ffi\")\n";
        out << "local C = require(\"kwxffi_gen\")\n";
        out << "local _H = require(\"kwxffi_helpers_gen\")\n";
        out << "\n";

        // Build the set of wrapped classes for parent resolution.
        std::unordered_set<std::string> wrapped_classes;
        for (const auto& other: ffi.classes)
        {
            if (!other.methods.empty() && other.name != "wxString")
                wrapped_classes.insert(other.name);
        }

        // Check for a wrapped parent to inherit methods from.
        std::string parent_name = FindWrappedParent(cls.name, ffi, wrapped_classes);

        if (!parent_name.empty())
        {
            std::string parent_file = LuaClassFileName(parent_name);
            // Strip the ".lua" for require (Lua require uses module names, not filenames)
            std::string parent_module = parent_file.substr(0, parent_file.size() - 4);
            out << "local _parent = require(\"" << parent_module << "\")\n";
            out << "local M = setmetatable({}, { __index = _parent })\n";
        }
        else
        {
            out << "local M = {}\n";
        }
        out << "local MT = { __index = M }\n";
        out << "\n";

        // Ptr accessor
        out << "--- Get the underlying C pointer.\n";
        out << "function M:Ptr() return self._ptr end\n";
        out << "\n";

        // ---------- Constructors ----------
        for (const auto& func: cls.methods)
        {
            if (!IsValidFunction(func))
                continue;
            if (!func.is_constructor || func.has_self)
                continue;  // Only true constructors (no self param)

            // Build idiomatic param list.
            std::vector<std::vector<LuaIdiomParam>> param_groups;
            for (const auto& param: func.params)
            {
                if (param.macro_name == "TSelf")
                    continue;
                auto group = ConvertToLuaIdiomParams(param, true);
                param_groups.push_back(std::move(group));
            }

            // Constructor function name: "Create" -> M.Create, "CreateEmpty" -> M.CreateEmpty
            out << "--- Constructor: " << CFuncName(func) << "\n";
            out << "function M." << func.method_name << "(";
            bool first_param = true;
            for (const auto& group: param_groups)
            {
                for (const auto& lp: group)
                {
                    if (!first_param)
                        out << ", ";
                    out << lp.name;
                    first_param = false;
                }
            }
            out << ")\n";

            // Pre-call statements.
            for (const auto& group: param_groups)
            {
                for (const auto& lp: group)
                {
                    if (!lp.pre_call.empty())
                        out << "    " << lp.pre_call << "\n";
                }
            }

            // C call.
            out << "    local ptr = C." << CFuncName(func) << "(";
            bool first_arg = true;
            for (const auto& group: param_groups)
            {
                for (const auto& lp: group)
                {
                    if (!first_arg)
                        out << ", ";
                    out << lp.call_expr;
                    first_arg = false;
                }
            }
            out << ")\n";

            // Post-call cleanup.
            for (const auto& group: param_groups)
            {
                for (const auto& lp: group)
                {
                    if (!lp.post_call.empty())
                        out << "    " << lp.post_call << "\n";
                }
            }

            // Null check and return.
            out << "    if ptr == nil then return nil end\n";
            out << "    return setmetatable({ _ptr = ptr }, MT)\n";
            out << "end\n";
            out << "\n";
        }

        // ---------- Methods (non-constructor, non-destructor) ----------
        for (const auto& func: cls.methods)
        {
            if (!IsValidFunction(func))
                continue;
            if (func.is_constructor && !func.has_self)
                continue;  // Already emitted above
            if (func.is_destructor)
                continue;  // Emitted separately below

            bool is_void = IsVoidReturn(func.return_type);

            // Build idiomatic param list (skip TSelf).
            std::vector<std::vector<LuaIdiomParam>> param_groups;
            bool has_post_calls = false;
            for (const auto& param: func.params)
            {
                if (param.macro_name == "TSelf")
                    continue;
                auto group = ConvertToLuaIdiomParams(param, false);
                for (const auto& lp: group)
                {
                    if (!lp.post_call.empty())
                        has_post_calls = true;
                }
                param_groups.push_back(std::move(group));
            }

            // Method signature: function M:MethodName(...)
            out << "function M:" << func.method_name << "(";
            bool first_param = true;
            for (const auto& group: param_groups)
            {
                for (const auto& lp: group)
                {
                    if (!first_param)
                        out << ", ";
                    out << lp.name;
                    first_param = false;
                }
            }
            out << ")\n";

            // Pre-call statements.
            for (const auto& group: param_groups)
            {
                for (const auto& lp: group)
                {
                    if (!lp.pre_call.empty())
                        out << "    " << lp.pre_call << "\n";
                }
            }

            // Build the C call expression.
            std::string c_call = "C." + CFuncName(func) + "(self._ptr";
            for (const auto& group: param_groups)
            {
                for (const auto& lp: group)
                {
                    c_call += ", " + lp.call_expr;
                }
            }
            c_call += ")";

            // Emit call and return.
            if (is_void)
            {
                out << "    " << c_call << "\n";
                for (const auto& group: param_groups)
                {
                    for (const auto& lp: group)
                    {
                        if (!lp.post_call.empty())
                            out << "    " << lp.post_call << "\n";
                    }
                }
            }
            else if (has_post_calls)
            {
                // Capture result, cleanup, then return.
                out << "    local _result = " << LuaReturnExpr(func, c_call) << "\n";
                for (const auto& group: param_groups)
                {
                    for (const auto& lp: group)
                    {
                        if (!lp.post_call.empty())
                            out << "    " << lp.post_call << "\n";
                    }
                }
                out << "    return _result\n";
            }
            else
            {
                out << "    return " << LuaReturnExpr(func, c_call) << "\n";
            }

            out << "end\n";
            out << "\n";
        }

        // ---------- Destructor ----------
        for (const auto& func: cls.methods)
        {
            if (!IsValidFunction(func) || !func.is_destructor)
                continue;

            // Check if this is a true destructor (no non-self params) or a list-item
            // delete (e.g., wxChoice_Delete(self, int index)).
            bool has_non_self_params = false;
            for (const auto& param: func.params)
            {
                if (param.macro_name != "TSelf")
                    has_non_self_params = true;
            }

            if (has_non_self_params)
            {
                // Not a true destructor — emit as a regular method.
                std::vector<std::vector<LuaIdiomParam>> param_groups;
                for (const auto& param: func.params)
                {
                    if (param.macro_name == "TSelf")
                        continue;
                    param_groups.push_back(ConvertToLuaIdiomParams(param, false));
                }

                out << "function M:" << func.method_name << "(";
                bool first_param = true;
                for (const auto& group: param_groups)
                {
                    for (const auto& lp: group)
                    {
                        if (!first_param)
                            out << ", ";
                        out << lp.name;
                        first_param = false;
                    }
                }
                out << ")\n";

                std::string c_call = "C." + CFuncName(func) + "(self._ptr";
                for (const auto& group: param_groups)
                {
                    for (const auto& lp: group)
                    {
                        c_call += ", " + lp.call_expr;
                    }
                }
                c_call += ")";

                bool is_void = IsVoidReturn(func.return_type);
                if (is_void)
                    out << "    " << c_call << "\n";
                else
                    out << "    return " << LuaReturnExpr(func, c_call) << "\n";
                out << "end\n\n";
            }
            else
            {
                // True destructor: guard against double-delete.
                out << "--- Delete the underlying C++ object.\n";
                out << "function M:Delete()\n";
                out << "    if self._ptr ~= nil then\n";
                out << "        C." << CFuncName(func) << "(self._ptr)\n";
                out << "        self._ptr = nil\n";
                out << "    end\n";
                out << "end\n";
                out << "\n";
            }
        }

        out << "return M\n";
    }

    void LuaJITEmitter::GenerateIdiomaticClasses(const ParsedFFI& ffi, const fs::path& outDir)
    {
        // Master include file.
        auto master_path = outDir / "kwxffi_idiomatic_gen.lua";
        ConditionalFileWriter master(master_path);
        if (!master.is_open())
        {
            std::cerr << "Error: cannot create " << master_path << "\n";
            return;
        }
        WriteGeneratedHeader(master, "--", false);
        master << "-- Master module for idiomatic LuaJIT wxWidgets wrappers.\n";
        master << "-- Usage: local wx = require(\"kwxffi_idiomatic_gen\")\n";
        master << "--        local btn = wx.wxButton.Create(parent, id, \"OK\", ...)\n";
        master << "--        btn:SetLabel(\"Cancel\")\n";
        master << "\n";
        master << "local M = {}\n";
        master << "\n";

        static const std::unordered_set<std::string> kSkipClass = {
            "wxString"  // Lifecycle managed by kwxffi_helpers_gen.lua
        };

        size_t class_count = 0;
        size_t skipped_count = 0;
        size_t method_count = 0;

        for (const auto& cls: ffi.classes)
        {
            if (cls.methods.empty())
                continue;
            if (kSkipClass.count(cls.name))
            {
                ++skipped_count;
                continue;
            }

            std::string file_name = LuaClassFileName(cls.name);
            auto file_path = outDir / file_name;

            ConditionalFileWriter out(file_path);
            if (!out.is_open())
            {
                std::cerr << "Error: cannot create " << file_path << "\n";
                continue;
            }
            ++class_count;

            EmitIdiomaticClassFile(out, cls, ffi);

            for (const auto& func: cls.methods)
            {
                if (IsValidFunction(func))
                    ++method_count;
            }

            // require module name = filename without .lua extension
            std::string module_name = file_name.substr(0, file_name.size() - 4);
            master << "M." << cls.name << " = require(\"" << module_name << "\")\n";
        }

        master << "\nreturn M\n";

        std::cerr << "  kwxffi_idiomatic_gen.lua:    " << class_count << " classes, "
                  << method_count << " methods";
        if (skipped_count > 0)
            std::cerr << " (" << skipped_count << " skipped)";
        std::cerr << "\n";
    }

}  // namespace kwxgen
