// Generated by GitHub Copilot. Directed and reviewed by Ralph Walden.
// Licensed under Apache 2.0. This file is not subject to copyright.

#include "events_parser.h"

#include <fstream>
#include <iostream>
#include <regex>
#include <string>

namespace kwxgen
{

    std::vector<EventDecl> ParseEvents(const std::filesystem::path& filePath)
    {
        std::vector<EventDecl> results;
        std::ifstream file(filePath);
        if (!file.is_open())
        {
            std::cerr << "Error: cannot open " << filePath << "\n";
            return results;
        }

        // Matches (both forms after exp_wxEVT_* rename):
        //   int exp_wxEVT_NAME();
        //   WXFFI_EXPORT(int, exp_wxEVT_NAME)();
        // Group 1 = export_name ("exp_wxEVT_BUTTON")
        // Group 2 = EVT_ suffix  ("EVT_BUTTON")  => event_name = "wx" + group2
        std::regex re(
            R"(^\s*(?:int|WXFFI_EXPORT\s*\(\s*int\s*,)\s*(exp_wx(EVT_\w+))\s*\)?\s*\(\s*\)\s*;)");
        std::string line;
        while (std::getline(file, line))
        {
            std::smatch m;
            if (std::regex_search(line, m, re))
            {
                EventDecl decl;
                decl.export_name = m[1].str();        // "exp_wxEVT_BUTTON"
                decl.event_name = "wx" + m[2].str();  // "wxEVT_BUTTON"
                results.push_back(std::move(decl));
            }
        }
        return results;
    }

}  // namespace kwxgen
