// Generated by GitHub Copilot. Directed and reviewed by Ralph Walden.
// Licensed under Apache 2.0. This file is not subject to copyright.

#include "exports_gen.h"

#include "file_writer.h"

#include <algorithm>
#include <iostream>

namespace fs = std::filesystem;

namespace kwxgen
{

std::vector<std::string> CollectExportSymbols(const ParsedFFI& ffi)
{
    std::vector<std::string> symbols;

    // Class methods — use the original C symbol name.
    for (auto& cls: ffi.classes)
    {
        for (auto& m: cls.methods)
        {
            if (!m.c_func_name.empty())
                symbols.push_back(m.c_func_name);
        }
    }

    // Event type exports (e.g., exp_wxEVT_BUTTON).
    for (auto& e: ffi.events)
        symbols.push_back(e.export_name);

    // Key code exports (e.g., exp_wxK_BACK).
    for (auto& k: ffi.keys)
        symbols.push_back(k.export_name);

    // Constants from kwx_defs.cpp and WXFFI_EXPORT in kwx_constants.h.
    for (auto& c: ffi.constants)
        symbols.push_back(c.export_name);

    // Free functions from kwx_constants.h and kwx_classes.h.
    for (auto& f: ffi.free_functions)
    {
        // Class-parser-sourced free functions have c_func_name set;
        // constants-parser-sourced ones only have method_name.
        if (!f.c_func_name.empty())
            symbols.push_back(f.c_func_name);
        else if (!f.method_name.empty())
            symbols.push_back(f.method_name);
    }

    // Sort and deduplicate for stable, deterministic output.
    std::sort(symbols.begin(), symbols.end());
    symbols.erase(std::unique(symbols.begin(), symbols.end()), symbols.end());

    return symbols;
}

void GenerateExportFiles(const ParsedFFI& ffi, const fs::path& outDir)
{
    fs::create_directories(outDir);
    auto symbols = CollectExportSymbols(ffi);

    size_t written = 0;

    // ---- Windows module-definition file (.def) ----
    {
        ConditionalFileWriter out(outDir / "kwxffi_exports.def");
        out << "; Generated by kwxgen -- do not edit\n";
        out << "EXPORTS\n";
        for (auto& sym: symbols)
            out << "    " << sym << "\n";
        if (out.Flush())
            ++written;
    }

    // ---- Linux linker version script (.map) ----
    {
        ConditionalFileWriter out(outDir / "kwxffi_exports.map");
        out << "/* Generated by kwxgen -- do not edit */\n";
        out << "{\n";
        out << "    global:\n";
        for (auto& sym: symbols)
            out << "        " << sym << ";\n";
        out << "    local: *;\n";
        out << "};\n";
        if (out.Flush())
            ++written;
    }

    // ---- macOS exported symbols list (.exp) ----
    {
        ConditionalFileWriter out(outDir / "kwxffi_exports.exp");
        out << "# Generated by kwxgen -- do not edit\n";
        for (auto& sym: symbols)
            out << "_" << sym << "\n";
        if (out.Flush())
            ++written;
    }

    std::cerr << "Exports: " << symbols.size() << " symbols, " << written
              << " of 3 files written to " << outDir << "\n";
}

}  // namespace kwxgen
