// Generated by GitHub Copilot. Directed and reviewed by Ralph Walden.
// Licensed under Apache 2.0. This file is not subject to copyright.

#include "parser_utils.h"

#include <cctype>
#include <string>
#include <unordered_set>
#include <vector>

namespace kwxgen
{

    std::string Trim(const std::string& s)
    {
        auto b = s.find_first_not_of(" \t\r\n");
        if (b == std::string::npos)
            return {};
        auto e = s.find_last_not_of(" \t\r\n");
        return s.substr(b, e - b + 1);
    }

    bool ParseMacroType(const std::string& type, std::string& macro_name, std::string& macro_arg)
    {
        // Match: WORD(CONTENT) where CONTENT may contain nested parens
        // e.g. TClass(wxWindow), TSelf(wxButton), TRect(x, y, w, h)
        auto paren = type.find('(');
        if (paren == std::string::npos || type.back() != ')')
        {
            macro_name.clear();
            macro_arg.clear();
            return false;
        }
        std::string prefix = type.substr(0, paren);
        // prefix must be a valid identifier
        if (prefix.empty() ||
            !(std::isalpha(static_cast<unsigned char>(prefix[0])) || prefix[0] == '_'))
        {
            macro_name.clear();
            macro_arg.clear();
            return false;
        }
        macro_name = prefix;
        macro_arg = type.substr(paren + 1, type.size() - paren - 2);
        return true;
    }

    std::vector<std::string> SplitParams(const std::string& paramStr)
    {
        std::vector<std::string> result;
        int depth = 0;
        size_t start = 0;
        for (size_t i = 0; i < paramStr.size(); ++i)
        {
            if (paramStr[i] == '(')
                ++depth;
            else if (paramStr[i] == ')')
                --depth;
            else if (paramStr[i] == ',' && depth == 0)
            {
                std::string token = Trim(paramStr.substr(start, i - start));
                if (!token.empty())
                    result.push_back(token);
                start = i + 1;
            }
        }
        // Last token
        if (start < paramStr.size())
        {
            std::string token = Trim(paramStr.substr(start));
            if (!token.empty())
                result.push_back(token);
        }
        return result;
    }

    Param ParseOneParam(const std::string& token)
    {
        Param p;

        // Try macro form: "MacroName(args) paramName" or "MacroName(args)"
        // Find the closing paren of the macro
        auto paren_open = token.find('(');
        if (paren_open != std::string::npos)
        {
            // Find the matching close paren
            int depth = 0;
            size_t paren_close = std::string::npos;
            for (size_t i = paren_open; i < token.size(); ++i)
            {
                if (token[i] == '(')
                    ++depth;
                else if (token[i] == ')')
                {
                    --depth;
                    if (depth == 0)
                    {
                        paren_close = i;
                        break;
                    }
                }
            }

            if (paren_close != std::string::npos)
            {
                std::string prefix = token.substr(0, paren_open);
                // Check if prefix is a valid macro identifier
                bool is_macro =
                    !prefix.empty() &&
                    (std::isalpha(static_cast<unsigned char>(prefix[0])) || prefix[0] == '_');
                for (size_t i = 1; is_macro && i < prefix.size(); ++i)
                    is_macro =
                        std::isalnum(static_cast<unsigned char>(prefix[i])) || prefix[i] == '_';

                if (is_macro)
                {
                    p.macro_name = prefix;
                    p.macro_arg = token.substr(paren_open + 1, paren_close - paren_open - 1);
                    p.raw_type = prefix + "(" + p.macro_arg + ")";

                    // Check for param name after closing paren
                    std::string rest = Trim(token.substr(paren_close + 1));
                    if (!rest.empty())
                    {
                        // Could be "* name" for pointer, or just "name"
                        if (rest[0] == '*')
                        {
                            p.raw_type += "*";
                            rest = Trim(rest.substr(1));
                        }
                        p.param_name = rest;
                    }
                    return p;
                }
            }
        }

        // Plain type: "int flags", "void* pointer", "double value", etc.
        auto last_space = token.rfind(' ');
        if (last_space != std::string::npos)
        {
            std::string maybe_name = Trim(token.substr(last_space + 1));
            std::string maybe_type = Trim(token.substr(0, last_space));

            // Check if maybe_name looks like an identifier (and isn't a keyword/type)
            bool is_ident = !maybe_name.empty() &&
                            (std::isalpha(static_cast<unsigned char>(maybe_name[0])) ||
                             maybe_name[0] == '_');
            for (size_t i = 1; is_ident && i < maybe_name.size(); ++i)
                is_ident = std::isalnum(static_cast<unsigned char>(maybe_name[i])) ||
                           maybe_name[i] == '_';

            static const std::unordered_set<std::string> type_keywords = { "int",    "void",
                                                                            "double", "float",
                                                                            "char",   "long" };
            if (is_ident && type_keywords.find(maybe_name) == type_keywords.end())
            {
                p.raw_type = maybe_type;
                p.param_name = maybe_name;
                return p;
            }
        }

        // No parameter name — type only
        p.raw_type = token;
        return p;
    }

}  // namespace kwxgen
