// Generated by GitHub Copilot. Directed and reviewed by Ralph Walden.
// Licensed under Apache 2.0. This file is not subject to copyright.

#include "kwx_wrapper.h"

#include <wx/sound.h>

#if defined(wxUSE_SOUND) && (wxUSE_SOUND == 0)
    #undef wxUSE_SOUND
#endif

#ifndef wxUSE_SOUND
    #define wxSound void
#endif

extern "C"
{
    EXPORT wxSound* wxSound_Create(wxString* fileName, bool isResource)
    {
        return new wxSound(*fileName, isResource);
    }

    EXPORT void wxSound_Delete(wxSound* self)
    {
        delete self;
    }

    EXPORT bool wxSound_IsOk(wxSound* self)
    {
        return self && self->IsOk();
    }

    EXPORT bool wxSound_Play(wxSound* self, unsigned flag)
    {
        return self && ((wxSoundBase*) self)->Play(flag);
    }

    EXPORT void wxSound_Stop(wxSound* self)
    {
        if (self)
             self->Stop();
    }
}
