// Generated by GitHub Copilot. Directed and reviewed by Ralph Walden.
// Licensed under Apache 2.0. This file is not subject to copyright.

#include "kwx_wrapper.h"
#include <wx/hyperlink.h>

// wxHyperlinkCtrl inherits from wxControl.
// Additional methods available via:
//   wxWindow_*  — base window methods (see wx_window.cpp)
//   wxControl_* — label, alignment (see wx_control.cpp)

extern "C"
{
    EXPORT wxHyperlinkCtrl* wxHyperlinkCtrl_Create(wxWindow* parent, int id, const wxString& label,
                                                   const wxString& url, int x, int y, int width,
                                                   int height, int style)
    {
        return new wxHyperlinkCtrl(parent, id, label, url, wxPoint(x, y), wxSize(width, height),
                                   style);
    }

    EXPORT wxColour* wxHyperlinkCtrl_GetHoverColour(wxHyperlinkCtrl* self)
    {
        wxColour* result = new wxColour();
        *result = self->GetHoverColour();
        return result;
    }

    EXPORT wxColour* wxHyperlinkCtrl_GetNormalColour(wxHyperlinkCtrl* self)
    {
        wxColour* result = new wxColour();
        *result = self->GetNormalColour();
        return result;
    }

    EXPORT wxString* wxHyperlinkCtrl_GetURL(wxHyperlinkCtrl* self)
    {
        wxString* result = new wxString();
        *result = self->GetURL();
        return result;
    }

    EXPORT bool wxHyperlinkCtrl_GetVisited(wxHyperlinkCtrl* self)
    {
        return self->GetVisited();
    }

    EXPORT wxColour* wxHyperlinkCtrl_GetVisitedColour(wxHyperlinkCtrl* self)
    {
        wxColour* result = new wxColour();
        *result = self->GetVisitedColour();
        return result;
    }

    EXPORT void wxHyperlinkCtrl_SetHoverColour(wxHyperlinkCtrl* self, const wxColour& colour)
    {
        self->SetHoverColour(colour);
    }

    EXPORT void wxHyperlinkCtrl_SetNormalColour(wxHyperlinkCtrl* self, const wxColour& colour)
    {
        self->SetNormalColour(colour);
    }

    EXPORT void wxHyperlinkCtrl_SetURL(wxHyperlinkCtrl* self, const wxString& url)
    {
        self->SetURL(url);
    }

    EXPORT void wxHyperlinkCtrl_SetVisited(wxHyperlinkCtrl* self, bool visited)
    {
        self->SetVisited(visited);
    }

    EXPORT void wxHyperlinkCtrl_SetVisitedColour(wxHyperlinkCtrl* self, const wxColour& colour)
    {
        self->SetVisitedColour(colour);
    }
}
