// Generated by GitHub Copilot. Directed and reviewed by Ralph Walden.
// Licensed under Apache 2.0. This file is not subject to copyright.

#include "kwx_wrapper.h"

// wxActivityIndicator inherits from wxControl.
// Additional methods available via:
//   wxWindow_*  — base window methods (see wx_window.cpp)
//   wxControl_* — label, alignment (see wx_control.cpp)

extern "C"
{
    EXPORT wxActivityIndicator* wxActivityIndicator_Create(wxWindow* parent, int id, int x, int y,
                                                           int width, int height, int style)
    {
        return new wxActivityIndicator(parent, id, wxPoint(x, y), wxSize(width, height), style);
    }

    EXPORT bool wxActivityIndicator_IsRunning(wxActivityIndicator* self)
    {
        return self->IsRunning();
    }

    EXPORT void wxActivityIndicator_Start(wxActivityIndicator* self)
    {
        self->Start();
    }

    EXPORT void wxActivityIndicator_Stop(wxActivityIndicator* self)
    {
        self->Stop();
    }
}
