// Generated by GitHub Copilot. Directed and reviewed by Ralph Walden.
// Licensed under Apache 2.0. This file is not subject to copyright.

#include "kwx_wrapper.h"

// wxBannerWindow inherits from wxWindow (not wxControl).
// Additional methods available via:
//   wxWindow_* — base window methods (see wx_window.cpp)

extern "C"
{
    EXPORT wxBannerWindow* wxBannerWindow_Create(wxWindow* parent, int id, int dir, int x, int y,
                                                 int width, int height, int style)
    {
        return new wxBannerWindow(parent, id, static_cast<wxDirection>(dir), wxPoint(x, y),
                                  wxSize(width, height), style);
    }

    EXPORT void wxBannerWindow_SetBitmap(wxBannerWindow* self, wxBitmap* bmp)
    {
        self->SetBitmap(*bmp);
    }

    EXPORT void wxBannerWindow_SetText(wxBannerWindow* self, wxString* title, wxString* message)
    {
        self->SetText(*title, *message);
    }

    EXPORT void wxBannerWindow_SetGradient(wxBannerWindow* self, wxColour* start, wxColour* end)
    {
        self->SetGradient(*start, *end);
    }
}
