// Generated by GitHub Copilot. Directed and reviewed by Ralph Walden.
// Licensed under Apache 2.0. This file is not subject to copyright.

#include "kwx_wrapper.h"

extern "C"
{
    EXPORT wxConfigBase* wxConfigBase_Create()
    {
        return wxConfigBase::Create();
    }

    EXPORT void wxConfigBase_Delete(wxConfigBase* self)
    {
        delete self;
    }

    EXPORT void wxConfigBase_SetPath(wxConfigBase* self, wxString* strPath)
    {
        self->SetPath(*strPath);
    }

    EXPORT wxString* wxConfigBase_GetPath(wxConfigBase* self)
    {
        wxString* result = new wxString();
        *result = self->GetPath();
        return result;
    }

    EXPORT wxString* wxConfigBase_GetFirstGroup(wxConfigBase* self, long* lIndex)
    {
        wxString* tmp;
        tmp = new wxString("");
        if (self->GetFirstGroup(*tmp, *lIndex))
        {
            *lIndex = -1;
        }
        return tmp;
    }

    EXPORT wxString* wxConfigBase_GetNextGroup(wxConfigBase* self, long* lIndex)
    {
        wxString* tmp;
        tmp = new wxString("");
        if (self->GetNextGroup(*tmp, *lIndex))
        {
            *lIndex = -1;
        }
        return tmp;
    }

    EXPORT wxString* wxConfigBase_GetFirstEntry(wxConfigBase* self, long* lIndex)
    {
        wxString* tmp;
        tmp = new wxString("");
        if (self->GetFirstEntry(*tmp, *lIndex))
        {
            *lIndex = -1;
        }
        return tmp;
    }

    EXPORT wxString* wxConfigBase_GetNextEntry(wxConfigBase* self, long* lIndex)
    {
        wxString* tmp;
        tmp = new wxString("");
        if (self->GetNextEntry(*tmp, *lIndex))
        {
            *lIndex = -1;
        }
        return tmp;
    }

    EXPORT size_t wxConfigBase_GetNumberOfEntries(wxConfigBase* self, bool bRecursive)
    {
        return self->GetNumberOfEntries(bRecursive);
    }

    EXPORT size_t wxConfigBase_GetNumberOfGroups(wxConfigBase* self, bool bRecursive)
    {
        return self->GetNumberOfGroups(bRecursive);
    }

    EXPORT bool wxConfigBase_HasGroup(wxConfigBase* self, wxString* strName)
    {
        return self->HasGroup(*strName);
    }

    EXPORT bool wxConfigBase_HasEntry(wxConfigBase* self, wxString* strName)
    {
        return self->HasEntry(*strName);
    }

    EXPORT bool wxConfigBase_Exists(wxConfigBase* self, wxString* strName)
    {
        return self->Exists(*strName);
    }

    EXPORT int wxConfigBase_GetEntryType(wxConfigBase* self, wxString* name)
    {
        return (int) self->GetEntryType(*name);
    }

    EXPORT wxString* wxConfigBase_ReadString(wxConfigBase* self, wxString* key, wxString* defVal)
    {
        wxString tmp;
        tmp = self->Read(*key, *defVal);
        return new wxString(tmp);
    }

    EXPORT int wxConfigBase_ReadInteger(wxConfigBase* self, wxString* key, int defVal)
    {
        return self->Read(*key, defVal);
    }

    EXPORT double wxConfigBase_ReadDouble(wxConfigBase* self, wxString* key, double defVal)
    {
        double val;
        if (self->Read(*key, &val, defVal))
            return val;
        return 0.0;
    }

    EXPORT bool wxConfigBase_ReadBool(wxConfigBase* self, wxString* key, bool defVal)
    {
        bool val;
        if (self->Read(*key, &val, defVal))
            return val;
        return false;
    }

    EXPORT bool wxConfigBase_WriteString(wxConfigBase* self, wxString* key, wxString* value)
    {
        return self->Write(*key, *value);
    }

    EXPORT bool wxConfigBase_WriteInteger(wxConfigBase* self, wxString* key, int value)
    {
        return self->Write(*key, (long) value);
    }

    EXPORT bool wxConfigBase_WriteLong(wxConfigBase* self, wxString* key, long value)
    {
        return self->Write(*key, value);
    }

    EXPORT bool wxConfigBase_WriteDouble(wxConfigBase* self, wxString* key, double value)
    {
        return self->Write(*key, value);
    }

    EXPORT bool wxConfigBase_WriteBool(wxConfigBase* self, wxString* key, bool value)
    {
        return self->Write(*key, value);
    }

    EXPORT bool wxConfigBase_Flush(wxConfigBase* self, bool bCurrentOnly)
    {
        return self->Flush(bCurrentOnly);
    }

    EXPORT bool wxConfigBase_RenameEntry(wxConfigBase* self, wxString* oldName, wxString* newName)
    {
        return self->RenameEntry(*oldName, *newName);
    }

    EXPORT bool wxConfigBase_RenameGroup(wxConfigBase* self, wxString* oldName, wxString* newName)
    {
        return self->RenameGroup(*oldName, *newName);
    }

    EXPORT bool wxConfigBase_DeleteEntry(wxConfigBase* self, wxString* key,
                                         bool bDeleteGroupIfEmpty)
    {
        return self->DeleteEntry(*key, bDeleteGroupIfEmpty);
    }

    EXPORT bool wxConfigBase_DeleteGroup(wxConfigBase* self, wxString* key)
    {
        return self->DeleteGroup(*key);
    }

    EXPORT bool wxConfigBase_DeleteAll(wxConfigBase* self)
    {
        return self->DeleteAll();
    }

    EXPORT bool wxConfigBase_IsExpandingEnvVars(wxConfigBase* self)
    {
        return self->IsExpandingEnvVars();
    }

    EXPORT void wxConfigBase_SetExpandEnvVars(wxConfigBase* self, bool bDoIt)
    {
        self->SetExpandEnvVars(bDoIt);
    }

    EXPORT void wxConfigBase_SetRecordDefaults(wxConfigBase* self, bool bDoIt)
    {
        self->SetRecordDefaults(bDoIt);
    }

    EXPORT bool wxConfigBase_IsRecordingDefaults(wxConfigBase* self)
    {
        return self->IsRecordingDefaults();
    }

    EXPORT wxString* wxConfigBase_ExpandEnvVars(wxConfigBase* self, wxString* str)
    {
        wxString* result = new wxString();
        *result = self->ExpandEnvVars(*str);
        return result;
    }

    EXPORT wxString* wxConfigBase_GetAppName(wxConfigBase* self)
    {
        wxString* result = new wxString();
        *result = self->GetAppName();
        return result;
    }

    EXPORT wxString* wxConfigBase_GetVendorName(wxConfigBase* self)
    {
        wxString* result = new wxString();
        *result = self->GetVendorName();
        return result;
    }

    EXPORT void wxConfigBase_SetAppName(wxConfigBase* self, wxString* appName)
    {
        self->SetAppName(*appName);
    }

    EXPORT void wxConfigBase_SetVendorName(wxConfigBase* self, wxString* vendorName)
    {
        self->SetVendorName(*vendorName);
    }

    EXPORT void wxConfigBase_SetStyle(wxConfigBase* self, int style)
    {
        self->SetStyle((long) style);
    }

    EXPORT long wxConfigBase_GetStyle(wxConfigBase* self)
    {
        return self->GetStyle();
    }
}
