// Generated by GitHub Copilot. Directed and reviewed by Ralph Walden.
// Licensed under Apache 2.0. This file is not subject to copyright.

#include "kwx_wrapper.h"

// wxDialog inherits from wxTopLevelWindow.
// Additional methods available via:
//   wxWindow_* — base window methods (see wx_window.cpp)

extern "C"
{
    EXPORT wxDialog* wxDialog_Create(wxWindow* parent, int id, wxString* title, int x, int y,
                                     int width, int height, int style)
    {
        return new wxDialog(parent, id, *title, wxPoint(x, y), wxSize(width, height), style);
    }

    EXPORT bool wxDialog_IsModal(wxDialog* self)
    {
        return self->IsModal();
    }

    EXPORT int wxDialog_ShowModal(wxDialog* self)
    {
        return self->ShowModal();
    }

    EXPORT void wxDialog_EndModal(wxDialog* self, int retCode)
    {
        self->EndModal(retCode);
    }

    EXPORT void wxDialog_SetReturnCode(wxDialog* self, int returnCode)
    {
        self->SetReturnCode(returnCode);
    }

    EXPORT int wxDialog_GetReturnCode(wxDialog* self)
    {
        return self->GetReturnCode();
    }

    EXPORT void wxDialog_SetAffirmativeId(wxDialog* self, int id)
    {
        self->SetAffirmativeId(id);
    }

    EXPORT int wxDialog_GetAffirmativeId(wxDialog* self)
    {
        return self->GetAffirmativeId();
    }

    EXPORT void wxDialog_SetEscapeId(wxDialog* self, int id)
    {
        self->SetEscapeId(id);
    }

    EXPORT int wxDialog_GetEscapeId(wxDialog* self)
    {
        return self->GetEscapeId();
    }

    EXPORT void* wxDialog_CreateButtonSizer(wxDialog* self, long flags)
    {
        return (void*) self->CreateButtonSizer(flags);
    }

    EXPORT void* wxDialog_CreateSeparatedButtonSizer(wxDialog* self, long flags)
    {
        return (void*) self->CreateSeparatedButtonSizer(flags);
    }

    EXPORT void* wxDialog_CreateStdDialogButtonSizer(wxDialog* self, long flags)
    {
        return (void*) self->CreateStdDialogButtonSizer(flags);
    }
}
