// Generated by GitHub Copilot. Directed and reviewed by Ralph Walden.
// Licensed under Apache 2.0. This file is not subject to copyright.

#include "kwx_wrapper.h"

extern "C"
{
    EXPORT void* wxFontData_Create()
    {
        return (void*) new wxFontData();
    }

    EXPORT void wxFontData_Delete(wxFontData* self)
    {
        delete self;
    }

    EXPORT void wxFontData_SetAllowSymbols(wxFontData* self, bool flag)
    {
        self->SetAllowSymbols(flag);
    }

    EXPORT bool wxFontData_GetAllowSymbols(wxFontData* self)
    {
        return self->GetAllowSymbols();
    }

    EXPORT void wxFontData_SetColour(wxFontData* self, wxColour* colour)
    {
        self->SetColour(*colour);
    }

    EXPORT void wxFontData_GetColour(wxFontData* self, wxColour* ref)
    {
        *ref = self->GetColour();
    }

    EXPORT void wxFontData_SetShowHelp(wxFontData* self, bool flag)
    {
        self->SetShowHelp(flag);
    }

    EXPORT bool wxFontData_GetShowHelp(wxFontData* self)
    {
        return self->GetShowHelp();
    }

    EXPORT void wxFontData_EnableEffects(wxFontData* self, bool flag)
    {
        self->EnableEffects(flag);
    }

    EXPORT bool wxFontData_GetEnableEffects(wxFontData* self)
    {
        return self->GetEnableEffects();
    }

    EXPORT void wxFontData_SetInitialFont(wxFontData* self, wxFont* font)
    {
        self->SetInitialFont(*font);
    }

    EXPORT void wxFontData_GetInitialFont(wxFontData* self, wxFont* ref)
    {
        *ref = self->GetInitialFont();
    }

    EXPORT void wxFontData_SetChosenFont(wxFontData* self, wxFont* font)
    {
        self->SetChosenFont(*font);
    }

    EXPORT void wxFontData_GetChosenFont(wxFontData* self, wxFont* ref)
    {
        *ref = self->GetChosenFont();
    }

    EXPORT void wxFontData_SetRange(wxFontData* self, int minRange, int maxRange)
    {
        self->SetRange(minRange, maxRange);
    }

    EXPORT int wxFontData_GetEncoding(wxFontData* self)
    {
        return (int) self->GetEncoding();
    }

    EXPORT void wxFontData_SetEncoding(wxFontData* self, int encoding)
    {
        self->SetEncoding((wxFontEncoding) encoding);
    }
}
