// Generated by GitHub Copilot. Directed and reviewed by Ralph Walden.
// Licensed under Apache 2.0. This file is not subject to copyright.

#include "kwx_wrapper.h"

extern "C"
{
    EXPORT void* wxLayoutConstraints_left(wxLayoutConstraints* self)
    {
        return (void*) (&self->left);
    }

    EXPORT void* wxLayoutConstraints_top(wxLayoutConstraints* self)
    {
        return (void*) (&self->top);
    }

    EXPORT void* wxLayoutConstraints_right(wxLayoutConstraints* self)
    {
        return (void*) (&self->right);
    }

    EXPORT void* wxLayoutConstraints_bottom(wxLayoutConstraints* self)
    {
        return (void*) (&self->bottom);
    }

    EXPORT void* wxLayoutConstraints_width(wxLayoutConstraints* self)
    {
        return (void*) (&self->width);
    }

    EXPORT void* wxLayoutConstraints_height(wxLayoutConstraints* self)
    {
        return (void*) (&self->height);
    }

    EXPORT void* wxLayoutConstraints_centreX(wxLayoutConstraints* self)
    {
        return (void*) (&self->centreX);
    }

    EXPORT void* wxLayoutConstraints_centreY(wxLayoutConstraints* self)
    {
        return (void*) (&self->centreY);
    }

    EXPORT void* wxLayoutConstraints_Create()
    {
        return (void*) new wxLayoutConstraints();
    }

    EXPORT void wxIndividualLayoutConstraint_Set(wxIndividualLayoutConstraint* self, int rel,
                                                 wxWindowBase* otherW, int otherE, int val,
                                                 int marg)
    {
        self->Set((wxRelationship) rel, otherW, (wxEdge) otherE, val, marg);
    }

    EXPORT void wxIndividualLayoutConstraint_LeftOf(wxIndividualLayoutConstraint* self,
                                                    wxWindowBase* sibling, int marg)
    {
        self->LeftOf(sibling, (wxEdge) marg);
    }

    EXPORT void wxIndividualLayoutConstraint_RightOf(wxIndividualLayoutConstraint* self,
                                                     wxWindowBase* sibling, int marg)
    {
        self->RightOf(sibling, (wxEdge) marg);
    }

    EXPORT void wxIndividualLayoutConstraint_Above(wxIndividualLayoutConstraint* self,
                                                   wxWindow* sibling, int marg)
    {
        self->Above(sibling, marg);
    }

    EXPORT void wxIndividualLayoutConstraint_Below(wxIndividualLayoutConstraint* self,
                                                   wxWindow* sibling, int marg)
    {
        self->Below(sibling, marg);
    }

    EXPORT void wxIndividualLayoutConstraint_SameAs(wxIndividualLayoutConstraint* self,
                                                    wxWindowBase* otherW, int edge, int marg)
    {
        self->SameAs(otherW, (wxEdge) edge, (wxEdge) marg);
    }

    EXPORT void wxIndividualLayoutConstraint_PercentOf(wxIndividualLayoutConstraint* self,
                                                       wxWindowBase* otherW, int which, int per)
    {
        self->PercentOf(otherW, (wxEdge) which, per);
    }

    EXPORT void wxIndividualLayoutConstraint_Absolute(wxIndividualLayoutConstraint* self, int val)
    {
        self->Absolute(val);
    }

    EXPORT void wxIndividualLayoutConstraint_Unconstrained(wxIndividualLayoutConstraint* self)
    {
        self->Unconstrained();
    }

    EXPORT void wxIndividualLayoutConstraint_AsIs(wxIndividualLayoutConstraint* self)
    {
        self->AsIs();
    }

    EXPORT void* wxIndividualLayoutConstraint_GetOtherWindow(wxIndividualLayoutConstraint* self)
    {
        return (void*) self->GetOtherWindow();
    }

    EXPORT int wxIndividualLayoutConstraint_GetMyEdge(wxIndividualLayoutConstraint* self)
    {
        return (int) self->GetMyEdge();
    }

    EXPORT void wxIndividualLayoutConstraint_SetEdge(wxIndividualLayoutConstraint* self, int which)
    {
        self->SetEdge((wxEdge) which);
    }

    EXPORT void wxIndividualLayoutConstraint_SetValue(wxIndividualLayoutConstraint* self, int value)
    {
        self->SetValue(value);
    }

    EXPORT int wxIndividualLayoutConstraint_GetMargin(wxIndividualLayoutConstraint* self)
    {
        return self->GetMargin();
    }

    EXPORT void wxIndividualLayoutConstraint_SetMargin(wxIndividualLayoutConstraint* self,
                                                       int margin)
    {
        self->SetMargin(margin);
    }

    EXPORT int wxIndividualLayoutConstraint_GetValue(wxIndividualLayoutConstraint* self)
    {
        return self->GetValue();
    }

    EXPORT int wxIndividualLayoutConstraint_GetPercent(wxIndividualLayoutConstraint* self)
    {
        return self->GetPercent();
    }

    EXPORT int wxIndividualLayoutConstraint_GetOtherEdge(wxIndividualLayoutConstraint* self)
    {
        return self->GetOtherEdge();
    }

    EXPORT bool wxIndividualLayoutConstraint_GetDone(wxIndividualLayoutConstraint* self)
    {
        return self->GetDone();
    }

    EXPORT void wxIndividualLayoutConstraint_SetDone(wxIndividualLayoutConstraint* self, bool done)
    {
        self->SetDone(done);
    }

    EXPORT int wxIndividualLayoutConstraint_GetRelationship(wxIndividualLayoutConstraint* self)
    {
        return self->GetRelationship();
    }

    EXPORT void wxIndividualLayoutConstraint_SetRelationship(wxIndividualLayoutConstraint* self,
                                                             int relationship)
    {
        self->SetRelationship((wxRelationship) relationship);
    }

    EXPORT bool wxIndividualLayoutConstraint_ResetIfWin(wxIndividualLayoutConstraint* self,
                                                        wxWindowBase* otherW)
    {
        return self->ResetIfWin(otherW);
    }

    EXPORT bool wxIndividualLayoutConstraint_SatisfyConstraint(wxIndividualLayoutConstraint* self,
                                                               void* constraints, wxWindowBase* win)
    {
        return self->SatisfyConstraint((wxLayoutConstraints*) constraints, win);
    }

    EXPORT int wxIndividualLayoutConstraint_GetEdge(wxIndividualLayoutConstraint* self, int which,
                                                    wxWindowBase* thisWin, wxWindowBase* other)
    {
        return self->GetEdge((wxEdge) which, thisWin, other);
    }
}
