// Generated by GitHub Copilot. Directed and reviewed by Ralph Walden.
// Licensed under Apache 2.0. This file is not subject to copyright.

#include "kwx_wrapper.h"

#if !defined(__WXGTK__)
    #include <wx/dcprint.h>
#endif

#if wxUSE_POSTSCRIPT
    #include <wx/dcps.h>
    #include <wx/generic/prntdlgg.h>
#else
    #define wxPostScriptDC void
#endif

extern "C"
{
    EXPORT void* wxPrinter_Create(void* data)
    {
        return (void*) new wxPrinter((wxPrintDialogData*) data);
    }

    EXPORT void wxPrinter_Delete(wxPrinter* self)
    {
        delete self;
    }

    EXPORT void* wxPrinter_CreateAbortWindow(wxPrinter* self, wxWindow* parent,
                                             wxPrintout* printout)
    {
        return (void*) self->CreateAbortWindow(parent, printout);
    }

    EXPORT void wxPrinter_ReportError(wxPrinter* self, wxWindow* parent, wxPrintout* printout,
                                      wxString* message)
    {
        self->ReportError(parent, printout, *message);
    }

    EXPORT void wxPrinter_GetPrintDialogData(wxPrinter* self, wxPrintDialogData* ref)
    {
        *ref = self->GetPrintDialogData();
    }

    EXPORT bool wxPrinter_GetAbort(wxPrinter* self)
    {
        return self->GetAbort();
    }

    EXPORT int wxPrinter_GetLastError(wxPrinter* self)
    {
        return self->GetLastError();
    }

    EXPORT bool wxPrinter_Setup(wxPrinter* self, wxWindow* parent)
    {
        return self->Setup(parent);
    }

    EXPORT bool wxPrinter_Print(wxPrinter* self, wxWindow* parent, wxPrintout* printout,
                                bool prompt)
    {
        return self->Print(parent, printout, prompt);
    }

    EXPORT void* wxPrinter_PrintDialog(wxPrinter* self, wxWindow* parent)
    {
        return (void*) self->PrintDialog(parent);
    }

    EXPORT void* kwxPrintout_Create(void* title, void* self, void* fnBeginDocument,
                                    void* fnEndDocument, void* fnBeginPrinting, void* fnEndPrinting,
                                    void* fnPreparePrinting, void* fnPrintPage, void* fnHasPage,
                                    void* DoOnPageInfo)
    {
        return (void*) new kwxPrintout(title, self, fnBeginDocument, fnEndDocument, fnBeginPrinting,
                                       fnEndPrinting, fnPreparePrinting, fnPrintPage, fnHasPage,
                                       DoOnPageInfo);
    }
    EXPORT void kwxPrintout_Delete(kwxPrintout* self)
    {
        delete self;
    }

    EXPORT wxString* kwxPrintout_GetTitle(kwxPrintout* self)
    {
        return new wxString(self->GetTitle());
    }

    EXPORT void* kwxPrintout_GetDC(kwxPrintout* self)
    {
        return (void*) self->GetDC();
    }

    EXPORT void kwxPrintout_SetDC(kwxPrintout* self, wxDC* dc)
    {
        self->SetDC(dc);
    }

    EXPORT void kwxPrintout_SetPageSizePixels(void* pObject, int width, int height)
    {
        ((kwxPrintout*) pObject)->SetPageSizePixels(width, height);
    }

    EXPORT void kwxPrintout_GetPageSizePixels(void* pObject, int* width, int* height)
    {
        ((kwxPrintout*) pObject)->GetPageSizePixels(width, height);
    }

    EXPORT void kwxPrintout_SetPageSizeMM(void* pObject, int width, int height)
    {
        ((kwxPrintout*) pObject)->SetPageSizeMM(width, height);
    }

    EXPORT void kwxPrintout_GetPageSizeMM(void* pObject, int* width, int* height)
    {
        ((kwxPrintout*) pObject)->GetPageSizeMM(width, height);
    }

    EXPORT void kwxPrintout_SetPPIScreen(void* pObject, int x, int y)
    {
        ((kwxPrintout*) pObject)->SetPPIScreen(x, y);
    }

    EXPORT void kwxPrintout_GetPPIScreen(void* pObject, int* x, int* y)
    {
        ((kwxPrintout*) pObject)->GetPPIScreen(x, y);
    }

    EXPORT void kwxPrintout_SetPPIPrinter(void* pObject, int x, int y)
    {
        ((kwxPrintout*) pObject)->SetPPIPrinter(x, y);
    }

    EXPORT void kwxPrintout_GetPPIPrinter(void* pObject, int* x, int* y)
    {
        ((kwxPrintout*) pObject)->GetPPIPrinter(x, y);
    }

    EXPORT bool kwxPrintout_IsPreview(kwxPrintout* self)
    {
        return self->IsPreview();
    }

    EXPORT void* wxPreviewCanvas_Create(void* preview, wxWindow* parent, int x, int y, int width,
                                        int height, int style)
    {
        return (void*) new wxPreviewCanvas((wxPrintPreviewBase*) preview, parent, wxPoint(x, y),
                                           wxSize(width, height), (long) style);
    }

    EXPORT void* kwxPreviewFrame_Create(void* pObject, void* init, void* createCanvas,
                                        void* createToolbar, void* preview, void* parent,
                                        void* title, int x, int y, int width, int height, int style)
    {
        return (void*) new kwxPreviewFrame(pObject, init, createCanvas, createToolbar, preview,
                                           parent, title, x, y, width, height, style);
    }

    EXPORT void kwxPreviewFrame_Initialize(kwxPreviewFrame* self)
    {
        self->Initialize();
    }

    EXPORT void kwxPreviewFrame_SetPreviewCanvas(kwxPreviewFrame* self, void* obj)
    {
        self->SetPreviewCanvas(obj);
    }

    EXPORT void kwxPreviewFrame_SetControlBar(kwxPreviewFrame* self, void* obj)
    {
        self->SetControlBar(obj);
    }

    EXPORT void kwxPreviewFrame_SetPrintPreview(kwxPreviewFrame* self, void* obj)
    {
        self->SetPrintPreview(obj);
    }

    EXPORT void* kwxPreviewFrame_GetPreviewCanvas(kwxPreviewFrame* self)
    {
        return (void*) self->GetPreviewCanvas();
    }

    EXPORT void* kwxPreviewFrame_GetControlBar(kwxPreviewFrame* self)
    {
        return (void*) self->GetControlBar();
    }

    EXPORT void* kwxPreviewFrame_GetPrintPreview(kwxPreviewFrame* self)
    {
        return (void*) self->GetPrintPreview();
    }

    EXPORT void* kwxPreviewControlBar_Create(void* preview, int buttons, wxWindow* parent,
                                             void* title, int x, int y, int width, int height,
                                             int style)
    {
        return (void*) new wxPreviewControlBar((wxPrintPreviewBase*) preview, (long) buttons,
                                               parent, wxPoint(x, y), wxSize(width, height),
                                               (long) style);
    }

    EXPORT void* wxPrintPreview_CreateFromDialogData(void* printout, void* printoutForPrinting,
                                                     void* data)
    {
        return (void*) new wxPrintPreview((wxPrintout*) printout, (wxPrintout*) printoutForPrinting,
                                          (wxPrintDialogData*) data);
    }

    EXPORT void* wxPrintPreview_CreateFromData(void* printout, void* printoutForPrinting,
                                               void* data)
    {
        return (void*) new wxPrintPreview((wxPrintout*) printout, (wxPrintout*) printoutForPrinting,
                                          (wxPrintData*) data);
    }

    EXPORT void wxPrintPreview_Delete(wxPrintPreview* self)
    {
        delete self;
    }

    EXPORT void wxPrintPreview_SetCurrentPage(wxPrintPreview* self, int pageNum)
    {
        self->SetCurrentPage(pageNum);
    }

    EXPORT int wxPrintPreview_GetCurrentPage(wxPrintPreview* self)
    {
        return self->GetCurrentPage();
    }

    EXPORT void wxPrintPreview_SetPrintout(wxPrintPreview* self, wxPrintout* printout)
    {
        self->SetPrintout(printout);
    }

    EXPORT void* wxPrintPreview_GetPrintout(wxPrintPreview* self)
    {
        return (void*) self->GetPrintout();
    }

    EXPORT void* wxPrintPreview_GetPrintoutForPrinting(wxPrintPreview* self)
    {
        return (void*) self->GetPrintoutForPrinting();
    }

    EXPORT void wxPrintPreview_SetFrame(wxPrintPreview* self, wxFrame* frame)
    {
        self->SetFrame(frame);
    }

    EXPORT void wxPrintPreview_SetCanvas(wxPrintPreview* self, wxPreviewCanvas* canvas)
    {
        self->SetCanvas(canvas);
    }

    EXPORT void* wxPrintPreview_GetFrame(wxPrintPreview* self)
    {
        return (void*) self->GetFrame();
    }

    EXPORT void* wxPrintPreview_GetCanvas(wxPrintPreview* self)
    {
        return (void*) self->GetCanvas();
    }

    EXPORT bool wxPrintPreview_PaintPage(wxPrintPreview* self, wxPreviewCanvas* canvas, wxDC* dc)
    {
        return self->PaintPage(canvas, *dc);
    }

    EXPORT bool wxPrintPreview_DrawBlankPage(wxPrintPreview* self, wxPreviewCanvas* canvas,
                                             wxDC* dc)
    {
        return self->DrawBlankPage(canvas, *dc);
    }

    EXPORT bool wxPrintPreview_RenderPage(wxPrintPreview* self, int pageNum)
    {
        return self->RenderPage(pageNum);
    }

    EXPORT void wxPrintPreview_GetPrintDialogData(wxPrintPreview* self, wxPrintDialogData* ref)
    {
        *ref = self->GetPrintDialogData();
    }

    EXPORT void wxPrintPreview_SetZoom(wxPrintPreview* self, int percent)
    {
        self->SetZoom(percent);
    }

    EXPORT int wxPrintPreview_GetZoom(wxPrintPreview* self)
    {
        return self->GetZoom();
    }

    EXPORT int wxPrintPreview_GetMaxPage(wxPrintPreview* self)
    {
        return self->GetMaxPage();
    }

    EXPORT int wxPrintPreview_GetMinPage(wxPrintPreview* self)
    {
        return self->GetMinPage();
    }

    EXPORT bool wxPrintPreview_IsOk(wxPrintPreview* self)
    {
        return self->IsOk();
    }

    EXPORT void wxPrintPreview_SetOk(wxPrintPreview* self, bool isOk)
    {
        self->SetOk(isOk);
    }

    EXPORT bool wxPrintPreview_Print(wxPrintPreview* self, bool interactive)
    {
        return self->Print(interactive);
    }

    EXPORT void wxPrintPreview_DetermineScaling(wxPrintPreview* self)
    {
        self->DetermineScaling();
    }

    EXPORT void* wxPrintData_Create()
    {
        return (void*) new wxPrintData();
    }

    EXPORT void wxPrintData_Delete(wxPrintData* self)
    {
        delete self;
    }

    EXPORT void* wxPostScriptPrintNativeData_Create()
    {
#if wxUSE_POSTSCRIPT
        return (void*) new wxPostScriptPrintNativeData();
#else
        return nullptr;
#endif
    }

    EXPORT void wxPostScriptPrintNativeData_Delete(wxPostScriptPrintNativeData* self)
    {
#if wxUSE_POSTSCRIPT
        delete self;
#endif
    }

    EXPORT int wxPrintData_GetNoCopies(wxPrintData* self)
    {
        return self->GetNoCopies();
    }

    EXPORT bool wxPrintData_GetCollate(wxPrintData* self)
    {
        return self->GetCollate();
    }

    EXPORT int wxPrintData_GetOrientation(wxPrintData* self)
    {
        return self->GetOrientation();
    }

    EXPORT wxString* wxPrintData_GetPrinterName(wxPrintData* self)
    {
        return new wxString(self->GetPrinterName());
    }

    EXPORT bool wxPrintData_GetColour(wxPrintData* self)
    {
        return self->GetColour();
    }

    EXPORT int wxPrintData_GetDuplex(wxPrintData* self)
    {
        return (int) self->GetDuplex();
    }

    EXPORT int wxPrintData_GetPaperId(wxPrintData* self)
    {
        return (int) self->GetPaperId();
    }

    EXPORT wxSize* wxPrintData_GetPaperSize(wxPrintData* self)
    {
        wxSize* s = new wxSize();
        *s = self->GetPaperSize();
        return s;
    }

    EXPORT int wxPrintData_GetQuality(wxPrintData* self)
    {
        return (int) self->GetQuality();
    }

    EXPORT void wxPrintData_SetNoCopies(wxPrintData* self, int value)
    {
        self->SetNoCopies(value);
    }

    EXPORT void wxPrintData_SetCollate(wxPrintData* self, bool flag)
    {
        self->SetCollate(flag);
    }

    EXPORT void wxPrintData_SetOrientation(wxPrintData* self, int orient)
    {
        self->SetOrientation((wxPrintOrientation) orient);
    }

    EXPORT void wxPrintData_SetPrinterName(wxPrintData* self, wxString* name)
    {
        self->SetPrinterName(*name);
    }

    EXPORT void wxPrintData_SetColour(wxPrintData* self, bool colour)
    {
        self->SetColour(colour);
    }

    EXPORT void wxPrintData_SetDuplex(wxPrintData* self, int duplex)
    {
        self->SetDuplex((wxDuplexMode) duplex);
    }

    EXPORT void wxPrintData_SetPaperId(wxPrintData* self, int sizeId)
    {
        self->SetPaperId((wxPaperSize) sizeId);
    }

    EXPORT void wxPrintData_SetPaperSize(wxPrintData* self, int width, int height)
    {
        self->SetPaperSize(wxSize(width, height));
    }

    EXPORT void wxPrintData_SetQuality(wxPrintData* self, int quality)
    {
        self->SetQuality((wxPrintQuality) quality);
    }

    EXPORT wxString* wxPrintData_GetPrinterCommand(wxPostScriptPrintNativeData* self)
    {
#if wxUSE_POSTSCRIPT
        wxString tmp = self->GetPrinterCommand();
        return new wxString(tmp);
#else
        return nullptr;
#endif
    }

    EXPORT wxString* wxPrintData_GetPrinterOptions(wxPostScriptPrintNativeData* self)
    {
#if wxUSE_POSTSCRIPT
        wxString tmp = self->GetPrinterOptions();
        return new wxString(tmp);
#else
        return nullptr;
#endif
    }

    EXPORT wxString* wxPrintData_GetPreviewCommand(wxPostScriptPrintNativeData* self)
    {
#if wxUSE_POSTSCRIPT
        wxString tmp = self->GetPreviewCommand();
        return new wxString(tmp);
#else
        return nullptr;
#endif
    }

    EXPORT wxString* wxPrintData_GetFilename(wxPrintData* self)
    {
        wxString tmp = self->GetFilename();
        return new wxString(tmp);
    }

    EXPORT wxString* wxPrintData_GetFontMetricPath(wxPostScriptPrintNativeData* self)
    {
#if wxUSE_POSTSCRIPT
        wxString tmp = self->GetFontMetricPath();
        return new wxString(tmp);
#else
        return nullptr;
#endif
    }

    EXPORT double wxPrintData_GetPrinterScaleX(wxPostScriptPrintNativeData* self)
    {
#if wxUSE_POSTSCRIPT
        return self->GetPrinterScaleX();
#else
        return 0.0;
#endif
    }

    EXPORT double wxPrintData_GetPrinterScaleY(wxPostScriptPrintNativeData* self)
    {
#if wxUSE_POSTSCRIPT
        return self->GetPrinterScaleY();
#else
        return 0.0;
#endif
    }

    EXPORT int wxPrintData_GetPrinterTranslateX(wxPostScriptPrintNativeData* self)
    {
#if wxUSE_POSTSCRIPT
        return self->GetPrinterTranslateX();
#else
        return 0;
#endif
    }

    EXPORT int wxPrintData_GetPrinterTranslateY(wxPostScriptPrintNativeData* self)
    {
#if wxUSE_POSTSCRIPT
        return self->GetPrinterTranslateY();
#else
        return 0;
#endif
    }

    EXPORT int wxPrintData_GetPrintMode(wxPrintData* self)
    {
        return (int) self->GetPrintMode();
    }

    EXPORT void wxPrintData_SetPrinterCommand(wxPostScriptPrintNativeData* self, wxString* command)
    {
#if wxUSE_POSTSCRIPT
        self->SetPrinterCommand(*command);
#endif
    }

    EXPORT void wxPrintData_SetPrinterOptions(wxPostScriptPrintNativeData* self, wxString* options)
    {
#if wxUSE_POSTSCRIPT
        self->SetPrinterOptions(*options);
#endif
    }

    EXPORT void wxPrintData_SetPreviewCommand(wxPostScriptPrintNativeData* self, wxString* command)
    {
#if wxUSE_POSTSCRIPT
        self->SetPreviewCommand(*command);
#endif
    }

    EXPORT void wxPrintData_SetFilename(wxPrintData* self, wxString* filename)
    {
        self->SetFilename(*filename);
    }

    EXPORT void wxPrintData_SetFontMetricPath(wxPostScriptPrintNativeData* self, wxString* path)
    {
#if wxUSE_POSTSCRIPT
        self->SetFontMetricPath(*path);
#endif
    }

    EXPORT void wxPrintData_SetPrinterScaleX(wxPostScriptPrintNativeData* self, double x)
    {
#if wxUSE_POSTSCRIPT
        self->SetPrinterScaleX(x);
#endif
    }

    EXPORT void wxPrintData_SetPrinterScaleY(wxPostScriptPrintNativeData* self, double y)
    {
#if wxUSE_POSTSCRIPT
        self->SetPrinterScaleY(y);
#endif
    }

    EXPORT void wxPrintData_SetPrinterScaling(wxPostScriptPrintNativeData* self, double x, double y)
    {
#if wxUSE_POSTSCRIPT
        self->SetPrinterScaling(x, y);
#endif
    }

    EXPORT void wxPrintData_SetPrinterTranslateX(wxPostScriptPrintNativeData* self, int x)
    {
#if wxUSE_POSTSCRIPT
        self->SetPrinterTranslateX((int) x);
#endif
    }

    EXPORT void wxPrintData_SetPrinterTranslateY(wxPostScriptPrintNativeData* self, int y)
    {
#if wxUSE_POSTSCRIPT
        self->SetPrinterTranslateY((int) y);
#endif
    }

    EXPORT void wxPrintData_SetPrinterTranslation(wxPostScriptPrintNativeData* self, int x, int y)
    {
#if wxUSE_POSTSCRIPT
        self->SetPrinterTranslation((long) x, (long) y);
#endif
    }

    EXPORT void wxPrintData_SetPrintMode(wxPrintData* self, int printMode)
    {
        self->SetPrintMode((wxPrintMode) printMode);
    }

    EXPORT void wxPrintData_Assign(wxPrintData* self, void* data)
    {
        *self = *((wxPrintData*) data);
    }

    EXPORT void* wxPrintDialogData_CreateDefault()
    {
        return (void*) new wxPrintDialogData();
    }

    EXPORT void* wxPrintDialogData_CreateFromData(void* printData)
    {
        return (void*) new wxPrintDialogData(*((wxPrintData*) printData));
    }

    EXPORT void wxPrintDialogData_Delete(wxPrintDialogData* self)
    {
        delete self;
    }

    EXPORT int wxPrintDialogData_GetFromPage(wxPrintDialogData* self)
    {
        return self->GetFromPage();
    }

    EXPORT int wxPrintDialogData_GetToPage(wxPrintDialogData* self)
    {
        return self->GetToPage();
    }

    EXPORT int wxPrintDialogData_GetMinPage(wxPrintDialogData* self)
    {
        return self->GetMinPage();
    }

    EXPORT int wxPrintDialogData_GetMaxPage(wxPrintDialogData* self)
    {
        return self->GetMaxPage();
    }

    EXPORT int wxPrintDialogData_GetNoCopies(wxPrintDialogData* self)
    {
        return self->GetNoCopies();
    }

    EXPORT bool wxPrintDialogData_GetAllPages(wxPrintDialogData* self)
    {
        return self->GetAllPages();
    }

    EXPORT bool wxPrintDialogData_GetSelection(wxPrintDialogData* self)
    {
        return self->GetSelection();
    }

    EXPORT bool wxPrintDialogData_GetCollate(wxPrintDialogData* self)
    {
        return self->GetCollate();
    }

    EXPORT bool wxPrintDialogData_GetPrintToFile(wxPrintDialogData* self)
    {
        return self->GetPrintToFile();
    }

    EXPORT void wxPrintDialogData_SetFromPage(wxPrintDialogData* self, int value)
    {
        self->SetFromPage(value);
    }

    EXPORT void wxPrintDialogData_SetToPage(wxPrintDialogData* self, int value)
    {
        self->SetToPage(value);
    }

    EXPORT void wxPrintDialogData_SetMinPage(wxPrintDialogData* self, int value)
    {
        self->SetMinPage(value);
    }

    EXPORT void wxPrintDialogData_SetMaxPage(wxPrintDialogData* self, int value)
    {
        self->SetMaxPage(value);
    }

    EXPORT void wxPrintDialogData_SetNoCopies(wxPrintDialogData* self, int value)
    {
        self->SetNoCopies(value);
    }

    EXPORT void wxPrintDialogData_SetAllPages(wxPrintDialogData* self, bool flag)
    {
        self->SetAllPages(flag);
    }

    EXPORT void wxPrintDialogData_SetSelection(wxPrintDialogData* self, bool flag)
    {
        self->SetSelection(flag);
    }

    EXPORT void wxPrintDialogData_SetCollate(wxPrintDialogData* self, bool flag)
    {
        self->SetCollate(flag);
    }

    EXPORT void wxPrintDialogData_SetPrintToFile(wxPrintDialogData* self, bool flag)
    {
        self->SetPrintToFile(flag);
    }

    EXPORT void wxPrintDialogData_EnablePrintToFile(wxPrintDialogData* self, bool flag)
    {
        self->EnablePrintToFile(flag);
    }

    EXPORT void wxPrintDialogData_EnableSelection(wxPrintDialogData* self, bool flag)
    {
        self->EnableSelection(flag);
    }

    EXPORT void wxPrintDialogData_EnablePageNumbers(wxPrintDialogData* self, bool flag)
    {
        self->EnablePageNumbers(flag);
    }

    EXPORT void wxPrintDialogData_EnableHelp(wxPrintDialogData* self, bool flag)
    {
        self->EnableHelp(flag);
    }

    EXPORT bool wxPrintDialogData_GetEnablePrintToFile(wxPrintDialogData* self)
    {
        return self->GetEnablePrintToFile();
    }

    EXPORT bool wxPrintDialogData_GetEnableSelection(wxPrintDialogData* self)
    {
        return self->GetEnableSelection();
    }

    EXPORT bool wxPrintDialogData_GetEnablePageNumbers(wxPrintDialogData* self)
    {
        return self->GetEnablePageNumbers();
    }

    EXPORT bool wxPrintDialogData_GetEnableHelp(wxPrintDialogData* self)
    {
        return self->GetEnableHelp();
    }

    EXPORT void wxPrintDialogData_GetPrintData(wxPrintDialogData* self, wxPrintData* ref)
    {
        *ref = self->GetPrintData();
    }

    EXPORT void wxPrintDialogData_SetPrintData(wxPrintDialogData* self, wxPrintData* printData)
    {
        self->SetPrintData(*printData);
    }

    EXPORT void wxPrintDialogData_Assign(wxPrintDialogData* self, wxPrintDialogData* data)
    {
        *self = *data;
    }

    EXPORT void wxPrintDialogData_AssignData(wxPrintDialogData* self, wxPrintData* data)
    {
        *self = *data;
    }

    EXPORT wxPostScriptDC* wxPostScriptDC_Create(wxPrintData* printData)
    {
#if wxUSE_POSTSCRIPT
        return new wxPostScriptDC(*printData);
#else
        return nullptr;
#endif
    }

    EXPORT void wxPostScriptDC_Delete(wxPostScriptDC* self)
    {
#if wxUSE_POSTSCRIPT
        if (self)
            delete self;
#endif
    }

    EXPORT void wxPostScriptDC_SetResolution(wxPostScriptDC* self, int ppi)
    {
        // SetResolution was removed in wxWidgets 2.9+
    }

    EXPORT int wxPostScriptDC_GetResolution(wxPostScriptDC* self, int ppi)
    {
#if wxUSE_POSTSCRIPT
        return self->GetResolution();
#else
        return 0;
#endif
    }

    EXPORT void* wxPrinterDC_Create(wxPrintData* printData)
    {
#if defined(__WXGTK__)
        return nullptr;
#else
        return new wxPrinterDC(*printData);
#endif
    }

    EXPORT void wxPrinterDC_Delete(wxPrinterDC* self)
    {
#if !defined(__WXGTK__)
        delete self;
#endif
    }

    EXPORT wxRect* wxPrinterDC_GetPaperRect(wxPrinterDC* self)
    {
#if !defined(__WXGTK__)
        wxRect* rct = new wxRect();
        *rct = self->GetPaperRect();
        return rct;
#else
        return 0;
#endif
    }
}
